package org.openelisglobal.microbiology.valueholder;

public enum MicroCaseActivityType {
    CASE_CREATED, STAGE_CHANGED, ISOLATE_CREATED, ISOLATE_UPDATED, AST_RUN_CREATED, AST_READING_RECORDED,
    AST_READING_OVERRIDDEN, AST_REVIEWED, CRITICAL_COMMUNICATION_LOGGED, CRITICAL_COMMUNICATION_ACKNOWLEDGED,
    CRITICAL_COMMUNICATION_CLOSED, PRELIMINARY_REPORT_RELEASED, FINAL_REPORT_RELEASED, ORDER_DETAIL_CAPTURED,
    AMENDMENT_OPENED, AMENDMENT_RELEASED, AMENDMENT_CANCELLED, AST_REPORTABLE_SELECTED, WORKFLOW_CHANGED,
    INOCULATION_RECORDED, SUBCULTURE_RECORDED, MANUAL_NOTE, NONCONFORMANCE_REPORTED, SPECIMEN_LOST,
    AST_ANALYZER_RESULTS_RECEIVED, AST_ANALYZER_QC_FAILED, AST_RUN_INVALIDATED, AST_QC_OVERRIDDEN,
    AST_ANALYZER_FLAGS_ACKNOWLEDGED, CULTURE_PROTOCOL_CHANGED
}
