package org.openelisglobal.microbiology.valueholder;

public enum MicroCaseStage {
    RECEIVED, SETUP_RECORDED, INCUBATING, GROWTH_DETECTED, NO_GROWTH_READY, IDENTIFICATION, AST_READY, AST_IN_PROGRESS,
    REVIEW_READY, PRELIM_RELEASED, FINAL_RELEASED, AMENDED, REJECTED
}
