package org.openelisglobal.microbiology.valueholder;

public enum MicroCaseActivityType {
    CASE_CREATED, STAGE_CHANGED, ISOLATE_CREATED, ISOLATE_UPDATED, ORDER_DETAIL_CAPTURED, AST_RUN_CREATED,
    AST_READING_RECORDED, AST_READING_OVERRIDDEN, AST_REVIEWED
}
