package org.openelisglobal.qaevent;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;
import org.junit.Before;
import org.junit.Test;
import org.openelisglobal.BaseWebContextSensitiveTest;
import org.openelisglobal.qaevent.service.NCEventService;
import org.openelisglobal.qaevent.service.NceHistoryService;
import org.openelisglobal.qaevent.service.NceSpecimenService;
import org.openelisglobal.qaevent.service.QcViolationNceService;
import org.openelisglobal.qaevent.service.QcViolationNceServiceImpl;
import org.openelisglobal.qaevent.valueholder.NcEvent;
import org.openelisglobal.qaevent.valueholder.NceSpecimen;
import org.openelisglobal.qc.service.QCResultService;
import org.openelisglobal.qc.service.QCRuleViolationService;
import org.openelisglobal.qc.service.evaluator.RuleEvaluationResult;
import org.openelisglobal.qc.valueholder.QCResult;
import org.openelisglobal.qc.valueholder.QCRuleViolation;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * Integration tests for the Westgard-violation → NCE auto-create flow (OGC-701
 * / OGC-728). Dataset scenarios: analyzer 501 has an in-control QC 30 min
 * before the violation, analyzer 502's last in-control QC is 3 days old (24h
 * floor applies), analyzer 503 has 51 in-window analyses (count cap applies).
 */
public class QcViolationNceServiceTest extends BaseWebContextSensitiveTest {

    private static final Timestamp VIOLATION_TIME = Timestamp.valueOf("2025-06-10 12:00:00");

    @Autowired
    private QcViolationNceService qcViolationNceService;
    @Autowired
    private NCEventService ncEventService;
    @Autowired
    private NceSpecimenService nceSpecimenService;
    @Autowired
    private NceHistoryService nceHistoryService;
    @Autowired
    private QCRuleViolationService qcRuleViolationService;
    @Autowired
    private QCResultService qcResultService;

    @Before
    public void setUp() throws Exception {
        executeDataSetWithStateManagement("testdata/qc-violation-nce.xml");
    }

    private QCRuleViolation buildViolation(String id, String instrumentId, String ruleCode) {
        QCRuleViolation violation = new QCRuleViolation();
        violation.setId(id);
        violation.setInstrumentId(instrumentId);
        violation.setTestId("601");
        violation.setRuleCode(ruleCode);
        violation.setSeverity("REJECTION");
        violation.setViolationDateTime(VIOLATION_TIME);
        violation.setSystemUserId(1);
        violation.setResolutionNotes("Detection: single result exceeds 3SD");
        return violation;
    }

    private Set<Integer> linkedSampleItemIds(NcEvent nce) {
        return nceSpecimenService.getSpecimenByNceId(nce.getId()).stream().map(NceSpecimen::getSampleItemId)
                .collect(Collectors.toSet());
    }

    @Test
    public void createNceForViolation_shouldCreateCriticalPendingNceWithViolationContext() {
        NcEvent nce = qcViolationNceService.createNceForViolation(buildViolation("wg-vio-a", "501", "1₃ₛ"));

        assertNotNull(nce.getId());
        assertEquals("CRITICAL", nce.getSeverity());
        assertEquals("Pending", nce.getStatus());
        assertEquals(Boolean.TRUE, nce.getAutoGenerated());
        assertEquals(QcViolationNceServiceImpl.TRIGGER_SOURCE_QC_VIOLATION, nce.getTriggerSourceType());
        assertEquals("wg-vio-a", nce.getTriggerSourceId());
        assertEquals("1₃ₛ", nce.getWestgardRule());
        assertTrue("NCE number should match generator format",
                nce.getNceNumber() != null && nce.getNceNumber().matches("NCE-\\d{4}-\\d{5}"));
        assertTrue("title should name the analyzer", nce.getTitle().contains("WG-Analyzer-A"));
        assertTrue("description should carry the detection notes",
                nce.getDescription().contains("Detection: single result exceeds 3SD"));
        assertEquals("Sample run held pending review", nce.getImmediateAction());
        assertEquals("System (Westgard QC)", nce.getNameOfReporter());
        assertTrue("an AUTO_CREATED history entry should be logged", nceHistoryService.findByNceId(nce.getId()).stream()
                .anyMatch(history -> "AUTO_CREATED".equals(history.getActivity())));
    }

    @Test
    public void createNceForViolation_shouldLinkDistinctSamplesSinceLastInControlQcAndDedupeRevisions() {
        NcEvent nce = qcViolationNceService.createNceForViolation(buildViolation("wg-vio-a2", "501", "1₃ₛ"));

        // 801 predates the 11:30 in-control QC (excluded); 9004 is another test
        // (excluded);
        // sample 802 has two in-window revisions (9002, 9005) → one link with the
        // latest.
        assertEquals(QcViolationNceServiceImpl.CAP_NONE_APPLIED, nce.getAffectedSamplesCapReason());
        assertEquals(Set.of(802, 803), linkedSampleItemIds(nce));
        assertEquals("revisions of the same sample collapse to one link", 2,
                nceSpecimenService.getSpecimenByNceId(nce.getId()).size());
        NceSpecimen sample802 = nceSpecimenService.getSpecimenByNceId(nce.getId()).stream()
                .filter(s -> Integer.valueOf(802).equals(s.getSampleItemId())).findFirst().orElseThrow();
        assertEquals("the latest revision is linked", Integer.valueOf(9005), sample802.getAnalysisId());
    }

    @Test
    public void createNceForViolation_shouldBeIdempotentPerViolation() {
        QCRuleViolation violation = buildViolation("wg-vio-idem", "501", "1₃ₛ");

        NcEvent first = qcViolationNceService.createNceForViolation(violation);
        NcEvent second = qcViolationNceService.createNceForViolation(violation);

        assertEquals(first.getId(), second.getId());
        assertEquals(first.getNceNumber(), second.getNceNumber());
        assertEquals(2, nceSpecimenService.getSpecimenByNceId(first.getId()).size());
    }

    @Test
    public void createNceForViolation_shouldFloorWindowAt24hWhenLastInControlQcIsStale() {
        NcEvent nce = qcViolationNceService.createNceForViolation(buildViolation("wg-vio-b", "502", "R₄ₛ"));

        // last in-control QC is 3 days old, so the window floors to 24h; sample 804
        // (completed before the floor) is excluded but proves older samples existed,
        // so the reason is time_24h.
        assertEquals(QcViolationNceServiceImpl.CAP_TIME_24H, nce.getAffectedSamplesCapReason());
        assertEquals(Set.of(805, 806), linkedSampleItemIds(nce));
    }

    @Test
    public void createNceForViolation_shouldReportNoneAppliedWhenNothingWasTrimmed() {
        // Analyzer 504 has no in-control QC and no samples before the 24h floor, so
        // nothing was actually excluded — the reason must be none_applied, not
        // time_24h.
        NcEvent nce = qcViolationNceService.createNceForViolation(buildViolation("wg-vio-d", "504", "1₃ₛ"));

        assertEquals(QcViolationNceServiceImpl.CAP_NONE_APPLIED, nce.getAffectedSamplesCapReason());
        assertEquals(Set.of(807), linkedSampleItemIds(nce));
    }

    @Test
    public void createNceForViolation_shouldCapAtFiftyNewestDistinctSamples() {
        NcEvent nce = qcViolationNceService.createNceForViolation(buildViolation("wg-vio-c", "503", "10ₓ"));

        Set<Integer> linkedSamples = linkedSampleItemIds(nce);
        assertEquals(QcViolationNceServiceImpl.CAP_COUNT_50, nce.getAffectedSamplesCapReason());
        assertEquals(50, linkedSamples.size());
        assertTrue("newest sample must be linked", linkedSamples.contains(950));
        assertFalse("oldest sample must be the one dropped", linkedSamples.contains(900));
    }

    @Test
    public void createViolation_shouldAutoCreateNceOnlyForRejectionSeverity() {
        QCResult triggeringResult = qcResultService.get("wg-qcr-a-trigger");
        assertNotNull(triggeringResult);

        RuleEvaluationResult warning = new RuleEvaluationResult.Builder("1₂ₛ").violated(true).severity("WARNING")
                .message("single result exceeds 2SD").build();
        QCRuleViolation warningViolation = qcRuleViolationService.createViolation(warning, triggeringResult);
        assertNotNull(warningViolation);
        assertNull("WARNING violations must not auto-create an NCE", ncEventService
                .findByTriggerSource(QcViolationNceServiceImpl.TRIGGER_SOURCE_QC_VIOLATION, warningViolation.getId()));

        RuleEvaluationResult rejection = new RuleEvaluationResult.Builder("1₃ₛ").violated(true).severity("REJECTION")
                .message("single result exceeds 3SD").build();
        QCRuleViolation rejectionViolation = qcRuleViolationService.createViolation(rejection, triggeringResult);
        assertNotNull(rejectionViolation);
        NcEvent nce = ncEventService.findByTriggerSource(QcViolationNceServiceImpl.TRIGGER_SOURCE_QC_VIOLATION,
                rejectionViolation.getId());
        assertNotNull("REJECTION violations must auto-create an NCE", nce);
        assertEquals("CRITICAL", nce.getSeverity());
    }

    // Regression for the concurrency bug found via the mock-server QC burst: one
    // failing QC run breaches several analytes at once, so many REJECTION
    // violations create NCEs concurrently. MAX(sequence)+1 raced and collided on
    // the nce_number unique constraint, silently losing NCEs. Each violation must
    // still get its own NCE with a distinct number.
    @Test
    public void createNceForViolation_isConcurrencySafeUnderSimultaneousViolations() throws Exception {
        int n = 8;
        CountDownLatch startGate = new CountDownLatch(1);
        ExecutorService pool = Executors.newFixedThreadPool(n);
        try {
            List<Future<NcEvent>> futures = new java.util.ArrayList<>();
            for (int i = 0; i < n; i++) {
                String violationId = "wg-conc-" + i;
                futures.add(pool.submit(() -> {
                    startGate.await();
                    return qcViolationNceService.createNceForViolation(buildViolation(violationId, "501", "1₃ₛ"));
                }));
            }
            startGate.countDown(); // release all threads at once to maximize contention

            Set<String> nceNumbers = new HashSet<>();
            for (Future<NcEvent> future : futures) {
                NcEvent nce = future.get(30, TimeUnit.SECONDS);
                assertNotNull(nce);
                nceNumbers.add(nce.getNceNumber());
            }
            assertEquals("each concurrent violation gets a distinct NCE number", n, nceNumbers.size());
        } finally {
            pool.shutdownNow();
        }
    }
}
