package org.openelisglobal.qaevent;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.time.LocalDate;
import java.util.ArrayList;
import org.junit.Before;
import org.junit.Test;
import org.openelisglobal.BaseWebContextSensitiveTest;
import org.openelisglobal.analysis.service.AnalysisService;
import org.openelisglobal.analysis.valueholder.Analysis;
import org.openelisglobal.note.service.NoteService;
import org.openelisglobal.note.service.NoteServiceImpl.NoteType;
import org.openelisglobal.note.valueholder.Note;
import org.openelisglobal.qaevent.service.NCEventService;
import org.openelisglobal.qaevent.service.TestRejectionNceService;
import org.openelisglobal.qaevent.service.TestRejectionNceServiceImpl;
import org.openelisglobal.qaevent.valueholder.NcEvent;
import org.openelisglobal.reports.rejection.bean.RejectionDetailResponse;
import org.openelisglobal.reports.rejection.service.RejectionReportService;
import org.openelisglobal.result.action.util.ResultsUpdateDataSet;
import org.openelisglobal.result.service.LogbookResultsPersistService;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * Integration tests for the test-rejection → NCE auto-create flow (per-row NCE
 * links on the rejection detail page). Fixture testdata/result.xml: analysis 2
 * belongs to sample 13333 / test "Urinalysis"; system_user 1 is John Doe.
 */
public class TestRejectionNceServiceTest extends BaseWebContextSensitiveTest {

    @Autowired
    private TestRejectionNceService testRejectionNceService;
    @Autowired
    private LogbookResultsPersistService logbookPersistService;
    @Autowired
    private NCEventService ncEventService;
    @Autowired
    private AnalysisService analysisService;
    @Autowired
    private NoteService noteService;
    @Autowired
    private RejectionReportService rejectionReportService;

    @Before
    public void setUp() throws Exception {
        executeDataSetWithStateManagement("testdata/result.xml");
    }

    private Note rejectionNote(String analysisId, String reason) {
        Analysis analysis = analysisService.get(analysisId);
        return noteService.createSavableNote(analysis, NoteType.REJECTION_REASON, reason, "Rejection Reason", "1");
    }

    @Test
    public void createForRejection_opensMinorPendingNceWithRejectionContext() {
        NcEvent nce = testRejectionNceService.createForRejection(rejectionNote("2", "Hemolyzed specimen"));

        assertNotNull(nce.getId());
        assertNotNull(nce.getNceNumber());
        assertEquals("MINOR", nce.getSeverity());
        assertEquals("Pending", nce.getStatus());
        assertEquals(Boolean.TRUE, nce.getAutoGenerated());
        assertEquals(TestRejectionNceServiceImpl.TRIGGER_SOURCE_TEST_REJECTION, nce.getTriggerSourceType());
        assertEquals("2", nce.getTriggerSourceId());
        assertTrue(nce.getTitle().contains("Urinalysis"));
        assertTrue(nce.getTitle().contains("13333"));
        assertTrue(nce.getDescription().contains("Hemolyzed specimen"));
        assertEquals("John Doe", nce.getNameOfReporter());
        // the rejection's bench (fixture analysis 2 -> test_sect_id 2) so the
        // NCE detail view can name a reporting unit
        assertEquals(Integer.valueOf(2), nce.getReportingUnitId());
    }

    @Test
    public void createForRejection_isIdempotentPerAnalysis() {
        NcEvent first = testRejectionNceService.createForRejection(rejectionNote("2", "Hemolyzed specimen"));
        // a second reason on the same analysis reuses the same NCE
        NcEvent second = testRejectionNceService.createForRejection(rejectionNote("2", "Insufficient volume"));

        assertEquals(first.getId(), second.getId());
        assertEquals(first.getNceNumber(), second.getNceNumber());
    }

    @Test
    public void persistDataSet_createsNceForRejectionNotes_ignoresOtherNotes() {
        ResultsUpdateDataSet dataSet = new ResultsUpdateDataSet("1");
        dataSet.getNoteList().add(rejectionNote("2", "Hemolyzed specimen"));

        Analysis analysis = analysisService.get("1");
        dataSet.getNoteList()
                .add(noteService.createSavableNote(analysis, NoteType.EXTERNAL, "Result corrected", "Note", "1"));

        logbookPersistService.persistDataSet(dataSet, new ArrayList<>(), "1");

        NcEvent nce = ncEventService.findByTriggerSource(TestRejectionNceServiceImpl.TRIGGER_SOURCE_TEST_REJECTION,
                "2");
        assertNotNull(nce);
        assertNull(ncEventService.findByTriggerSource(TestRejectionNceServiceImpl.TRIGGER_SOURCE_TEST_REJECTION, "1"));

        // The rejection detail rows carry the NCE number (LEFT JOIN on the
        // trigger source), so the UI can link each rejection to its NCE.
        RejectionDetailResponse detail = rejectionReportService.getDetail(LocalDate.of(2025, 7, 1),
                LocalDate.of(2025, 7, 31), 0, 25);
        assertEquals(1, detail.getTotalCount());
        assertEquals(nce.getNceNumber(), detail.getItems().get(0).getNceNumber());
    }
}
