package org.openelisglobal.qaevent.service;

import java.sql.Date;
import java.util.Objects;
import org.openelisglobal.analysis.service.AnalysisService;
import org.openelisglobal.analysis.valueholder.Analysis;
import org.openelisglobal.common.log.LogEvent;
import org.openelisglobal.note.valueholder.Note;
import org.openelisglobal.qaevent.valueholder.NcEvent;
import org.openelisglobal.systemuser.service.SystemUserService;
import org.openelisglobal.systemuser.valueholder.SystemUser;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

@Service
public class TestRejectionNceServiceImpl implements TestRejectionNceService {

    public static final String TRIGGER_SOURCE_TEST_REJECTION = "TEST_REJECTION";

    // Rejections are routine bench events — MINOR, unlike the CRITICAL
    // QC-violation / QI-breach NCEs.
    private static final String NCE_SEVERITY = "MINOR";
    private static final String NCE_STATUS = "Pending";

    @Autowired
    private NCEventService ncEventService;
    @Autowired
    private NceNumberGeneratorService nceNumberGeneratorService;
    @Autowired
    private NceHistoryService nceHistoryService;
    @Autowired
    private AnalysisService analysisService;
    @Autowired
    private SystemUserService systemUserService;

    // REQUIRES_NEW mirrors QcViolationNceServiceImpl: the NCE commits on its
    // own, so a failure here never poisons the results-save transaction (the
    // hook also catches). Trade-off documented there — an outer rollback can
    // strand the NCE; the idempotency key makes the retried save reuse it.
    @Override
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public NcEvent createForRejection(Note rejectionNote) {
        String analysisId = rejectionNote.getReferenceId();
        NcEvent existing = ncEventService.findByTriggerSource(TRIGGER_SOURCE_TEST_REJECTION, analysisId);
        if (existing != null) {
            return existing;
        }

        Analysis analysis = analysisService.get(analysisId);
        if (analysis == null) {
            LogEvent.logWarn(this.getClass().getSimpleName(), "createForRejection",
                    "Rejection note references no analysis (id " + analysisId + ") — skipping NCE");
            return null;
        }
        String testName = analysis.getTest() != null ? analysis.getTest().getName() : "Unknown test";
        String labNumber = analysis.getSampleItem() != null && analysis.getSampleItem().getSample() != null
                ? analysis.getSampleItem().getSample().getAccessionNumber()
                : "unknown";
        String reason = rejectionNote.getText();
        String techUserId = rejectionNote.getSysUserId();

        NcEvent nce = new NcEvent();
        nce.setSysUserId(techUserId);
        nce.setNceNumber(nceNumberGeneratorService.generateNceNumber());
        nce.setSeverity(NCE_SEVERITY);
        nce.setStatus(NCE_STATUS);
        nce.setAutoGenerated(Boolean.TRUE);
        nce.setTriggerSourceType(TRIGGER_SOURCE_TEST_REJECTION);
        nce.setTriggerSourceId(analysisId);
        nce.setTitle("Test rejection — " + testName + " (" + labNumber + ")");
        nce.setDescription("Auto-created from a test rejection at results entry. Reason: " + reason + ".");
        nce.setImmediateAction("Follow up with the ordering site; recollect the specimen if required");
        nce.setNameOfReporter(reporterName(techUserId));
        nce.setReportDate(new Date(System.currentTimeMillis()));
        nce.setDateOfEvent(new Date(System.currentTimeMillis()));
        nce.setReportingUnitId(reportingUnitId(analysis));

        nce = ncEventService.save(nce);

        nceHistoryService.logActivity(nce.getId(), "AUTO_CREATED",
                "Auto-created from test rejection: " + testName + " (" + labNumber + ") — " + reason, null, null,
                parseUserId(techUserId));

        LogEvent.logInfo(this.getClass().getSimpleName(), "createForRejection",
                "Created " + nce.getNceNumber() + " for analysis " + analysisId);
        return nce;
    }

    /**
     * The rejection's bench: the analysis-level section when assigned, else the
     * test's home section (dev/legacy analyses often carry none).
     */
    private Integer reportingUnitId(Analysis analysis) {
        if (analysis.getTestSection() != null) {
            return Integer.valueOf(analysis.getTestSection().getId());
        }
        if (analysis.getTest() != null && analysis.getTest().getTestSection() != null) {
            return Integer.valueOf(analysis.getTest().getTestSection().getId());
        }
        return null;
    }

    private String reporterName(String techUserId) {
        try {
            SystemUser user = systemUserService.get(techUserId);
            if (user != null) {
                String name = (Objects.toString(user.getFirstName(), "") + " "
                        + Objects.toString(user.getLastName(), "")).trim();
                if (!name.isEmpty()) {
                    return name;
                }
            }
        } catch (RuntimeException e) {
            // fall through to the system label
        }
        return "System (Test rejection)";
    }

    private Integer parseUserId(String techUserId) {
        try {
            return Integer.valueOf(techUserId);
        } catch (NumberFormatException e) {
            return Integer.valueOf(1);
        }
    }
}
