version: '3.3'
services:
    oe.openelis.org:
        container_name: openelisglobal-webapp 
        build: .
        ports:
            - "8082:8080"
            - "8443:8443"
        volumes:
            - ./dev/plugins:/var/lib/openelis-global/plugins
            - ./dev/tomcat/oe_server.xml:/usr/local/tomcat/conf/server.xml
            -  lucene_index-vol:/var/lib/lucene_index
        secrets:
            - source: common.properties
        tty: true
        stdin_open: true
        entrypoint: bash
secrets:
  common.properties:
    file: ./dev/properties/common.properties
volumes:
    lucene_index-vol: