#!/bin/bash

#get location of this script
bashScriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

projectDir="${bashScriptDir}/../.."
buildscriptDir="${projectDir}/buildscripts"
liquibaseDir="${projectDir}/liquibase"

databaseUpdate () {
	echo "updating $2"
	if [ -z $3 ]
	then
		java -jar -Dfile.encoding=utf-8 ${liquibaseDir}/lib/liquibase-1.9.5.jar --classpath=${liquibaseDir}/lib/postgresql.jar --defaultsFile=${liquibaseDir}/liquibase.properties  --contexts=$1 --url=jdbc:postgresql://localhost:5432/$2 update
	else
		java -jar -Dfile.encoding=utf-8 ${liquibaseDir}/lib/liquibase-1.9.5.jar --classpath=${liquibaseDir}/lib/postgresql.jar --defaultsFile=${liquibaseDir}/liquibase.properties  --contexts=$1 --url=jdbc:postgresql://localhost:5432/$2 --password=$3 update
	fi
}

cd ${projectDir}

#build the war to be used
source build docker

#deploy the war to tomcat under different names
source deploy haitiOpenElis
source deploy CDIOpenElis
source deploy LNSP_HaitiOpenElis
source deploy CI_LNSPOpenElis
source deploy CDI_RegLabOpenElis
source deploy KenyaOpenElis
source deploy CI_IPCIOpenElis
source deploy CI_OpenElis
source deploy haitiOpenElis
source deploy haitiOpenElis

cd ${liquibaseDir}

#command		context		dbname
databaseUpdate CDIRetroCI cdielis
databaseUpdate haiti clinlims
databaseUpdate haitiLNSP lnsphaiti
databaseUpdate ciLNSP cilnsp
databaseUpdate CI_IPCI ci_ipci
databaseUpdate ci_regional ci_reg_lab
databaseUpdate Kenya kenya