#!/bin/bash
#This shell will build, package and deploy the various demo installations on a test machine
if [ -z $1 ]
then
    echo "Name of branch to build is required"
    exit 1
fi

echo Will build from $1
#cd source/openelisglobal-core
#git checkout -- app/src/build.properties
git pull origin
git checkout $1
if [ $? != 0 ]
then
    echo
    echo "branch is not local will try to create"
    echo 
    
    git checkout -b $1 origin/$1

    if [ $? != 0 ]
	then
	echo
	echo "$1 not found in main repository. Check name"
	exit 1 
    fi
fi

git rev-list HEAD | tac | nl | tail -n 1 | sed 's/\t/ hash-/g'  |sed 's/\s\{2,\}/revision-/g' > ../../version.txt 
cd ../..
sed '2!d' source/openelisglobal-core/app/src/build.properties  > build.txt

#build and package application
#LANG=en_US ant buildpackage
mvn package
if [ $? != 0 ]
then
    echo
    echo build failed
    exit $?
fi

#stop tomcat
sudo /etc/init.d/tomcat6 stop
#this will insure that we don't have stale compiled jsp files
sudo  rm -r /usr/share/tomcat6/work/Catalina/localhost/
wait

#install haitiOpenElis
if [ -f ./target/openElis.war ] 
then
   echo "installing haitiOpenElis"

   if [ -d /usr/share/tomcat6/webapps/haitiOpenElis ]
   then
       sudo rm -r /usr/share/tomcat6/webapps/haitiOpenElis
   fi		
   
   sudo cp target/openElis.war /usr/share/tomcat6/webapps/haitiOpenElis.war

   echo "installing CDIOpenElis"

   if [ -d /usr/share/tomcat6/webapps/CDIOpenElis ]
   then
       sudo rm -r /usr/share/tomcat6/webapps/CDIOpenElis
   fi		

   sudo  cp target/openElis.war /usr/share/tomcat6/webapps/CDIOpenElis.war

   echo "installing LNSP_HaitiOpenElis"

   if [ -d /usr/share/tomcat6/webapps/LNSP_HaitiOpenElis ]
   then
       sudo rm -r /usr/share/tomcat6/webapps/LNSP_HaitiOpenElis
   fi		

   sudo cp target/openElis.war /usr/share/tomcat6/webapps/LNSP_HaitiOpenElis.war

   echo "installing CI_LNSPOpenElis"

   if [ -d /usr/share/tomcat6/webapps/CI_LNSPOpenElis ]
   then
       sudo  rm -r /usr/share/tomcat6/webapps/CI_LNSPOpenElis
   fi		

   sudo cp target/openElis.war /usr/share/tomcat6/webapps/CI_LNSPOpenElis.war

   echo "installing CDI_RegLabOpenElis"

   if [ -d /usr/share/tomcat6/webapps/CDI_RegLabOpenElis ]
   then
       sudo  rm -r /usr/share/tomcat6/webapps/CDI_RegLabOpenElis
   fi		

   sudo cp target/openElis.war /usr/share/tomcat6/webapps/CDI_RegLabOpenElis.war

  echo "installing KenyaOpenElis"

   if [ -d /usr/share/tomcat6/webapps/KenyaOpenElis ]
   then
       sudo rm -r /usr/share/tomcat6/webapps/KenyaOpenElis
   fi

   sudo cp target/openElis.war /usr/share/tomcat6/webapps/KenyaOpenElis.war

#for new instance copy-modify from here to end marker 
   echo "installing CI_IPCIOpenElis"

   if [ -d /usr/share/tomcat6/webapps/CI_IPCIOpenElis ]
   then
       sudo rm -r /usr/share/tomcat6/webapps/CI_IPCIOpenElis
   fi		

   sudo cp target/openElis.war /usr/share/tomcat6/webapps/CI_IPCIOpenElis.war
#end marker
#CI_General version
echo "installing CI_OpenElis"

   if [ -d /usr/share/tomcat6/webapps/CI_OpenElis ]
   then
       sudo rm -r /usr/share/tomcat6/webapps/CI_OpenElis
   fi		

   sudo cp target/openElis.war /usr/share/tomcat6/webapps/CI_OpenElis.war






else
   echo "missing openElis.war file" 
fi

#update database
LANG=en_US.UTF-8 ant updateDB
wait

#restart tomcat
sudo /etc/init.d/tomcat6 start

#build installers while we wait
ant installers