# System Config properties
###### Un comment the properties below to overide the Configuration proporties from the DB
# ACCEPT_EXTERNAL_ORDERS=false
# ACCESSION_NUMBER_PREFIX=DEV01
# ACCESSION_NUMBER_VALIDATE=true
# ADDITIONAL_SITE_INFO=
# ALERT_FOR_INVALID_RESULTS=false
# ALLOW_DUPLICATE_NATIONAL_IDS=true
# ALLOW_DUPLICATE_SUBJECT_NUMBERS=true
# ALPHANUM_ACCESSION_PREFIX=
# ALT_ACCESSION_PREFIX=
# ALWAYS_VALIDATE_RESULTS=true
# AUTOFILL_COLLECTION_DATE=false
# AccessionFormat=SITEYEARNUM
# Addressline1label=Street
# Addressline2label=Camp/Commune
# Addressline3label=Town
# AmbiguousDateHolder=x
# AmbiguousDateValue=01
# BAR_CODE_TYPE=BARCODE
# BLOCK_LABEL_BARCODE_HEIGHT=25.4
# BLOCK_LABEL_BARCODE_WIDTH=76.2
# BLOCK_LABEL_FIELD_BLOCK_ID=true
# BLOCK_LABEL_FIELD_CASE_NUMBER=true
# BLOCK_LABEL_FIELD_PATIENT_ID=true
# BLOCK_LABEL_FIELD_SPECIMEN_TYPE=true
# CLOCK_24=true
# CONDENSE_NFS_PANEL=false
# CONTACT_TRACING=false
# DEFAULT_ALIQUOT_LABEL_PRINTED=1
# DEFAULT_BLOCK_LABEL_PRINTED=1
# DEFAULT_DATE_LOCALE=fr-FR
# DEFAULT_FREEZER_LABEL_PRINTED=1
# DEFAULT_LANG_LOCALE=en-US
# DEFAULT_NATIONALITY=
# DEFAULT_ORDER_LABEL_PRINTED=2
# DEFAULT_SLIDE_LABEL_PRINTED=1
# DEFAULT_SPECIMEN_LABEL_PRINTED=1
# ELECTRONIC_SIGNATURE_ENABLED=false
# ENABLE_CLIENT_REGISTRY=false
# EQA_ENABLED=false
# ESIG_SESSION_TIMEOUT_MINUTES=30
# FREEZER_LABEL_BARCODE_HEIGHT=25.4
# FREEZER_LABEL_BARCODE_WIDTH=76.2
# FREEZER_LABEL_FIELD_COLLECTION_DATE=true
# FREEZER_LABEL_FIELD_EXPIRY_DATE=true
# FREEZER_LABEL_FIELD_PATIENT_ID=true
# FREEZER_LABEL_FIELD_SPECIMEN_TYPE=true
# FREEZER_LABEL_FIELD_STORAGE_LOCATION=true
# FormFieldSet=CI_GENERAL
# GPS_ACCURACY_METERS=100
# GPS_ENABLED=false
# GPS_TIMEOUT_SECONDS=10
# GeographicUnit1Label=Region
# GeographicUnit2Label=District
# INFO_HIGHWAY_ENABLED=false
# LAB_DIRECTOR_NAME=\ 
# LAB_DIRECTOR_TITLE=\ 
# MAX_ALIQUOT_LABEL_PRINTED=1
# MAX_BLOCK_LABEL_PRINTED=1
# MAX_FREEZER_LABEL_PRINTED=1
# MAX_ORDER_LABEL_PRINTED=10
# MAX_REQUEST_LABEL_QUANTITY=100
# MAX_SLIDE_LABEL_PRINTED=1
# MAX_SPECIMEN_LABEL_PRINTED=1
# NEXT_VISIT_DATE_ON_WORKPLAN=false
# NONCONFORMITY_RECEPTION_AS_UNIT=true
# NONCONFORMITY_SAMPLE_COLLECTION_AS_UNIT=true
# NOTE_EXTERNAL_ONLY_FOR_VALIDATION=true
# ORDER_LABEL_BARCODE_HEIGHT=25.4
# ORDER_LABEL_BARCODE_WIDTH=76.2
# ORDER_LABEL_FIELD_PATIENT_DOB=true
# ORDER_LABEL_FIELD_PATIENT_ID=true
# ORDER_LABEL_FIELD_PATIENT_NAME=true
# ORDER_LABEL_FIELD_SITE_ID=true
# ORDER_PROGRAM=true
# OVERRIDE_DEFAULT_TRANSLATION=false
# PATIENT_ALIAS_ENABLED=false
# PATIENT_ALIAS_LABEL=
# PATIENT_DATA_ON_RESULTS_BY_ROLE=false
# PATIENT_GPS_CAPTURE_ENABLED=true
# PATIENT_ID_DOCUMENTS_LABEL=
# PATIENT_ID_REQUIRED=false
# PATIENT_NATIONALITY=true
# PATIENT_NATIONAL_ID_REQUIRED=true
# PATIENT_RESULTS_BMP_SMS_ENABLED=false
# PATIENT_RESULTS_SMPP_SMS_ENABLED=false
# PATIENT_RESULTS_SMTP_ENABLED=false
# PATIENT_SUBJECT_NUMBER_REQUIRED=false
# PHONE_FORMAT=xxxx-xxxx
# PHONE_FORMAT_LABEL=
# PHONE_INTERNATIONAL_FORMAT_LABEL=
# PHONE_INTERNATIONAL_VALIDATION=NONE
# PasswordRequirments=CDI
# PatientSearchEnabled=false
# PatientSearchPassword=
# PatientSearchURL=
# PatientSearchUserName=
# QA_SAMPLE_ID_REQUIRED=true
# QA_SORT_EVENT_LIST=false
# REQUIRE_LAB_UNIT_AT_LOGIN=false
# RESULTS_ENTRY_UNIFIED_ROUTE=false
# RESULTS_ON_WORKPLAN=false
# ReferingLabParentOrg=
# ReflexAction=LNSP_Haiti
# SIGNATURES_ON_NONCONFORMITY_REPORTS=false
# SLIDE_LABEL_BARCODE_HEIGHT=25.4
# SLIDE_LABEL_BARCODE_WIDTH=76.2
# SLIDE_LABEL_FIELD_BLOCK_ID=true
# SLIDE_LABEL_FIELD_CASE_NUMBER=true
# SLIDE_LABEL_FIELD_PATIENT_ID=true
# SLIDE_LABEL_FIELD_SLIDE_ID=true
# SLIDE_LABEL_FIELD_STAIN_TYPE=true
# SPECIMEN_LABEL_BARCODE_HEIGHT=25.4
# SPECIMEN_LABEL_BARCODE_WIDTH=76.2
# SPECIMEN_LABEL_FIELD_COLLECTED_BY=true
# SPECIMEN_LABEL_FIELD_COLLECTION_DATE=true
# SPECIMEN_LABEL_FIELD_PATIENT_DOB=true
# SPECIMEN_LABEL_FIELD_PATIENT_ID=true
# SPECIMEN_LABEL_FIELD_PATIENT_NAME=true
# SPECIMEN_LABEL_FIELD_PATIENT_SEX=true
# SPECIMEN_LABEL_FIELD_TESTS=true
# SUBJECT_ON_WORKPLAN=false
# SiteCode=DEV01
# SiteName=
# StatusRules=LNSP_haiti
# StringContext=CI
# TEST_NAME_AUGMENTED=true
# TRACK_PATIENT_PAYMENT=true
# TrainingInstallation=false
# USE_ALPHANUM_ACCESSION_PREFIX=false
# USE_ALT_ACCESSION_PREFIX=false
# USE_BILLING_REFERENCE_NUMBER=false
# USE_NEW_ADDRESS_HIERARCHY=true
# USE_PAGE_NUMBERS_ON_REPORTS=false
# UseExternalPatientInfo=false
# VALIDATE_PHONE_FORMAT=true
# VALIDATE_REJECTED_TESTS=true
# adult=Infinity
# allowResultRejection=false
# analysis.default.revision=0
# analysis.status.assigned=1
# analysis.status.canceled=2
# analysis.status.released=4
# analysis.status.result.completed=3
# autoFillTechNameBox=false
# autoFillTechNameUser=false
# boxLabelPrefix=BOX
# child=168
# condenseNSF=false
# configurationName=CI_GENERAL
# customCriticalMessage=Set new critical result message
# default.datasource=java\:comp/env/jdbc/LimsDS
# default.idSeparator=;
# dictionary.category.qaevent.type=Q
# dictionaryType=D
# domain.environmental=E
# domain.human=H
# enable.user.test.section=N
# failedValidationMarker=true
# fhirContainerTypeCode=434711009
# fhirContainerTypeDisplay=Specimen container
# fhirNonConformityCodes={"RECEIVED_DAMAGED"\:"281411007","RECEIVED_LEAKED"\:"281412000","MISSING"\:"281264009","REJECTED"\:"123840003"}
# firstNameCharset=.'a-z\u00E0\u00E2\u00E7\u00E9\u00E8\u00EA\u00EB\u00EE\u00EF\u00F4\u00FB\u00F9\u00FC\u00FF\u00F1\u00E6\u0153 -
# freezer.bacnet.udp.port=47808
# freezer.modbus.tcp.port=502
# headerLeftImage=
# headerRightImage=
# infant=12
# labDirectorName=
# labDirectorSignature=\ 
# languageSwitch=true
# lastNameCharset=.'a-z\u00E0\u00E2\u00E7\u00E9\u00E8\u00EA\u00EB\u00EE\u00EF\u00F4\u00FB\u00F9\u00FC\u00FF\u00F1\u00E6\u0153 -
# localization.en.BANNER_TEXT=Test LIMS
# localization.en.BILLING_REFERENCE_NUMBER_LABEL=URAP Number
# localization.fr.BANNER_TEXT=Test LIMS
# localization.fr.BILLING_REFERENCE_NUMBER_LABEL=N\u00B0 URAP
# login.user.change.allow.day=3
# login.user.expired.month=1
# login.user.expired.reminder.day=15
# malariaCaseReport=false
# malariaCaseReportURL=
# malariaSurveillanceReport=false
# malariaSurveillanceReportURL=
# new\ born=1
# notesRequiredForModifyResults=false
# page.defaultPageSize=20
# patientIdCharset=a-z0-9/\u00E0\u00E2\u00E7\u00E9\u00E8\u00EA\u00EB\u00EE\u00EF\u00F4\u00FB\u00F9\u00FC\u00FF\u00F1\u00E6\u0153
# patientSearchPassword=
# permissions.agent=Role
# programs=
# reflex_rules=
# releaseNumber=3.2.1.8
# reportResults=false
# reportsDirectory=/reports
# restrictFreeTextMethodEntry=false
# restrictFreeTextProviderEntry=false
# restrictFreeTextRefSiteEntry=false
# resultReportingURL=disable
# resultTechnicianName=false
# resultsResendTime=30
# roleRequiredForModifyResults=false
# sample.status.entry.1.complete=2
# sample.status.entry.2.complete=3
# sample.status.label.printed=8
# sample.status.quick.entry.complete=1
# sample.status.released=7
# siteOrganizationFhirUuid=
# testUsageAggregationPassword=
# testUsageAggregationUserName=
# testUsageReporting=false
# testUsageReportingURL=
# testUsageSendStatus=N/A
# userNameCharset=a-z\u00E0\u00E2\u00E7\u00E9\u00E8\u00EA\u00EB\u00EE\u00EF\u00F4\u00FB\u00F9\u00FC\u00FF\u00F1\u00E6\u0153 ._@-
# young\ child=60