package org.openelisglobal.qaevent.qiconfig;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.sql.DataSource;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openelisglobal.BaseWebContextSensitiveTest;
import org.openelisglobal.qaevent.qiconfig.breach.QiBreachEvaluatorService;
import org.openelisglobal.qaevent.qiconfig.breach.QiBreachNceService;
import org.openelisglobal.qaevent.qiconfig.breach.QiBreachNceServiceImpl;
import org.openelisglobal.qaevent.qiconfig.dto.QiConfigView;
import org.openelisglobal.qaevent.qiconfig.service.QiConfigService;
import org.openelisglobal.qaevent.service.NCEventService;
import org.openelisglobal.qaevent.service.NceHistoryService;
import org.openelisglobal.qaevent.valueholder.NcEvent;
import org.openelisglobal.referencetables.service.ReferenceTablesService;
import org.openelisglobal.reports.amendment.bean.AmendmentSummaryResponse;
import org.openelisglobal.reports.amendment.service.AmendmentReportService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * OGC-712 — QI threshold-breach auto-NCE against a real DB (no mocks). Covers
 * the NCE-creation core (fields, AUTO_CREATED history, per-period idempotency)
 * and the evaluator's decision path (breach fires, disabled short-circuits).
 * The AMENDMENT rate is the only in-scope indicator (see
 * QiBreachEvaluatorServiceImpl).
 *
 * <p>
 * The breach test derives the action threshold from the rate the amendment
 * report actually returns, so it stays deterministic regardless of any ambient
 * released/amended rows in the harness.
 */
public class QiBreachEvaluatorServiceIntegrationTest extends BaseWebContextSensitiveTest {

    private static final String USER = "1";
    private static final String QI_BREACH = QiBreachNceServiceImpl.TRIGGER_SOURCE_QI_BREACH;
    private static final String CURRENT_PERIOD = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM"));

    @Autowired
    private QiBreachEvaluatorService qiBreachEvaluatorService;
    @Autowired
    private QiBreachNceService qiBreachNceService;
    @Autowired
    private QiConfigService qiConfigService;
    @Autowired
    private AmendmentReportService amendmentReportService;
    @Autowired
    private NCEventService ncEventService;
    @Autowired
    private NceHistoryService nceHistoryService;
    @Autowired
    private ReferenceTablesService referenceTablesService;
    @Autowired
    private DataSource dataSource;

    private JdbcTemplate jdbc;

    @Before
    @Override
    public void setUp() throws Exception {
        super.setUp();
        jdbc = new JdbcTemplate(dataSource);
        clearQiBreachNces();
        jdbc.update("DELETE FROM clinlims.qi_config");
    }

    @After
    public void tearDown() {
        clearQiBreachNces();
        jdbc.update("DELETE FROM clinlims.qi_config");
    }

    // ---- NCE creation core (no amendment data needed) ----

    @Test
    public void createBreachNce_setsAutoGeneratedContextAndLogsHistory() {
        NcEvent nce = qiBreachNceService.createBreachNce("AMENDMENT", "2099-01", bd("50"), bd("2"), "LOWER_BETTER");

        assertNotNull(nce.getId());
        assertEquals("CRITICAL", nce.getSeverity());
        assertEquals("Pending", nce.getStatus());
        assertEquals(Boolean.TRUE, nce.getAutoGenerated());
        assertEquals(QI_BREACH, nce.getTriggerSourceType());
        assertEquals("AMENDMENT:2099-01", nce.getTriggerSourceId());
        assertTrue("NCE number should match generator format",
                nce.getNceNumber() != null && nce.getNceNumber().matches("NCE-\\d{4}-\\d{5}"));
        assertTrue("title should name the indicator + period",
                nce.getTitle().contains("AMENDMENT") && nce.getTitle().contains("2099-01"));
        assertEquals("System (QI monitoring)", nce.getNameOfReporter());
        assertTrue("an AUTO_CREATED history entry should be logged", nceHistoryService.findByNceId(nce.getId()).stream()
                .anyMatch(h -> "AUTO_CREATED".equals(h.getActivity())));
    }

    @Test
    public void createBreachNce_isIdempotentPerIndicatorAndPeriod() {
        NcEvent first = qiBreachNceService.createBreachNce("AMENDMENT", "2099-01", bd("50"), bd("2"), "LOWER_BETTER");
        NcEvent second = qiBreachNceService.createBreachNce("AMENDMENT", "2099-01", bd("60"), bd("2"), "LOWER_BETTER");
        assertEquals("same indicator+period must reuse the NCE", first.getId(), second.getId());

        NcEvent nextPeriod = qiBreachNceService.createBreachNce("AMENDMENT", "2099-02", bd("50"), bd("2"),
                "LOWER_BETTER");
        assertNotEquals("a new period re-fires a distinct NCE", first.getId(), nextPeriod.getId());
    }

    // ---- evaluator decision path ----

    @Test
    public void evaluate_amendmentDisabled_firesNothing() {
        // Disabled default short-circuits before any compute (711 contract).
        qiConfigService.saveIndicator("AMENDMENT", view(false, bd("0"), bd("2")), USER);
        qiBreachEvaluatorService.evaluateBreaches();
        assertEquals(0, qiBreachCount());
    }

    @Test
    public void evaluate_amendmentBreach_firesOneNcePerPeriod() throws Exception {
        seedAmendmentActivity();
        AmendmentSummaryResponse summary = amendmentReportService.getSummary(LocalDate.now().withDayOfMonth(1),
                LocalDate.now());
        assertNotNull("seed should produce released rows", summary.getRatePercent());
        assertTrue("seed should produce a non-zero amendment rate", summary.getRatePercent() > 0);

        // action below the actual rate → LOWER_BETTER breach; target below action.
        BigDecimal action = BigDecimal.valueOf(summary.getRatePercent() / 2.0);
        qiConfigService.saveIndicator("AMENDMENT", view(true, BigDecimal.ZERO, action), USER);

        qiBreachEvaluatorService.evaluateBreaches();

        NcEvent nce = ncEventService.findByTriggerSource(QI_BREACH, "AMENDMENT:" + CURRENT_PERIOD);
        assertNotNull("a breach in the current period must create an NCE", nce);
        assertEquals(Boolean.TRUE, nce.getAutoGenerated());
        assertEquals(1, qiBreachCount());

        // Re-running the evaluator in the same period must not duplicate.
        qiBreachEvaluatorService.evaluateBreaches();
        assertEquals("idempotent within the period", 1, qiBreachCount());
    }

    @Test
    public void evaluate_amendmentWithinThreshold_firesNothing() throws Exception {
        seedAmendmentActivity();
        // action at 100 (max) → a rate can never exceed it → no breach.
        qiConfigService.saveIndicator("AMENDMENT", view(true, BigDecimal.ZERO, new BigDecimal("100")), USER);
        qiBreachEvaluatorService.evaluateBreaches();
        NcEvent nce = ncEventService.findByTriggerSource(QI_BREACH, "AMENDMENT:" + CURRENT_PERIOD);
        assertNull("a rate within the action threshold must not create an NCE", nce);
    }

    // ---- helpers ----

    /**
     * Reuse the QC dataset's valid analyses: stamp a few as released this month and
     * add one corrected-result note so the amendment rate is non-zero for the
     * current period.
     */
    private void seedAmendmentActivity() throws Exception {
        executeDataSetWithStateManagement("testdata/qc-violation-nce.xml");
        jdbc.update("UPDATE clinlims.analysis SET released_date = now()"
                + " WHERE id IN ('9001','9002','9003','9004','9005')");
        Long analysisRef = Long.valueOf(referenceTablesService.getReferenceTableByName("ANALYSIS").getId());
        jdbc.update("INSERT INTO clinlims.note (id, sys_user_id, reference_id, reference_table, note_type, text,"
                + " lastupdated) VALUES (nextval('clinlims.note_seq'), 1, 9001, ?, 'E', 'Result corrected', now())",
                analysisRef);
    }

    private void clearQiBreachNces() {
        jdbc.update("DELETE FROM clinlims.nce_history WHERE nce_id IN"
                + " (SELECT id FROM clinlims.nc_event WHERE trigger_source_type = ?)", QI_BREACH);
        jdbc.update("DELETE FROM clinlims.nc_event WHERE trigger_source_type = ?", QI_BREACH);
    }

    private int qiBreachCount() {
        return jdbc.queryForObject("SELECT COUNT(*) FROM clinlims.nc_event WHERE trigger_source_type = ?",
                Integer.class, QI_BREACH);
    }

    private static BigDecimal bd(String s) {
        return new BigDecimal(s);
    }

    private static QiConfigView view(boolean enabled, BigDecimal target, BigDecimal action) {
        QiConfigView v = new QiConfigView();
        v.setEnabled(enabled);
        v.setTarget(target);
        v.setAction(action);
        return v;
    }
}
