package org.openelisglobal.qaevent.qiconfig;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.UUID;
import javax.sql.DataSource;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openelisglobal.BaseWebContextSensitiveTest;
import org.openelisglobal.qaevent.criticalcallback.bean.CallbackSummaryResponse;
import org.openelisglobal.qaevent.criticalcallback.service.CriticalCallbackService;
import org.openelisglobal.qaevent.qiconfig.breach.QiBreachEvaluatorService;
import org.openelisglobal.qaevent.qiconfig.breach.QiBreachNceService;
import org.openelisglobal.qaevent.qiconfig.breach.QiBreachNceServiceImpl;
import org.openelisglobal.qaevent.qiconfig.dto.QiConfigView;
import org.openelisglobal.qaevent.qiconfig.service.QiConfigService;
import org.openelisglobal.qaevent.service.NCEventService;
import org.openelisglobal.qaevent.service.NceHistoryService;
import org.openelisglobal.qaevent.valueholder.NcEvent;
import org.openelisglobal.referencetables.service.ReferenceTablesService;
import org.openelisglobal.reports.amendment.bean.AmendmentSummaryResponse;
import org.openelisglobal.reports.amendment.service.AmendmentReportService;
import org.openelisglobal.reports.rejection.bean.RejectionSummaryResponse;
import org.openelisglobal.reports.rejection.service.RejectionReportService;
import org.openelisglobal.reports.tat.bean.TATCalculationMode;
import org.openelisglobal.reports.tat.bean.TATSegment;
import org.openelisglobal.reports.tat.bean.TATSummaryResponse;
import org.openelisglobal.reports.tat.service.TATReportService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * OGC-712 — QI threshold-breach auto-NCE against a real DB (no mocks). Covers
 * the NCE-creation core (fields, AUTO_CREATED history, per-period idempotency)
 * and the evaluator's decision path for all three threshold-bearing indicators
 * (AMENDMENT/REJECTION rates, TAT mean hours — see
 * QiBreachEvaluatorServiceImpl).
 *
 * <p>
 * The breach tests derive the action threshold from the value the metric
 * service actually returns, so they stay deterministic regardless of any
 * ambient rows in the harness.
 */
public class QiBreachEvaluatorServiceIntegrationTest extends BaseWebContextSensitiveTest {

    private static final String USER = "1";
    private static final String QI_BREACH = QiBreachNceServiceImpl.TRIGGER_SOURCE_QI_BREACH;
    private static final String CURRENT_PERIOD = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM"));
    // Self-seeded callback fixture ids, clear of the shared QC dataset's range.
    private static final long CALLBACK_TEST_ID = 95451L;
    private static final long CALLBACK_ANALYSIS_ID = 95451L;

    @Autowired
    private QiBreachEvaluatorService qiBreachEvaluatorService;
    @Autowired
    private QiBreachNceService qiBreachNceService;
    @Autowired
    private QiConfigService qiConfigService;
    @Autowired
    private AmendmentReportService amendmentReportService;
    @Autowired
    private RejectionReportService rejectionReportService;
    @Autowired
    private TATReportService tatReportService;
    @Autowired
    private CriticalCallbackService criticalCallbackService;
    @Autowired
    private NCEventService ncEventService;
    @Autowired
    private NceHistoryService nceHistoryService;
    @Autowired
    private ReferenceTablesService referenceTablesService;
    @Autowired
    private DataSource dataSource;

    private JdbcTemplate jdbc;

    @Before
    @Override
    public void setUp() throws Exception {
        super.setUp();
        jdbc = new JdbcTemplate(dataSource);
        clearQiBreachNces();
        clearCallbackSeed();
        jdbc.update("DELETE FROM clinlims.qi_config");
    }

    @After
    public void tearDown() {
        clearQiBreachNces();
        clearCallbackSeed();
        jdbc.update("DELETE FROM clinlims.qi_config");
    }

    // ---- NCE creation core (no amendment data needed) ----

    @Test
    public void createBreachNce_setsAutoGeneratedContextAndLogsHistory() {
        NcEvent nce = qiBreachNceService.createBreachNce("AMENDMENT", "2099-01", bd("50"), bd("2"), "LOWER_BETTER",
                "%");

        assertNotNull(nce.getId());
        assertEquals("CRITICAL", nce.getSeverity());
        assertEquals("Pending", nce.getStatus());
        assertEquals(Boolean.TRUE, nce.getAutoGenerated());
        assertEquals(QI_BREACH, nce.getTriggerSourceType());
        assertEquals("AMENDMENT:2099-01", nce.getTriggerSourceId());
        assertTrue("NCE number should match generator format",
                nce.getNceNumber() != null && nce.getNceNumber().matches("NCE-\\d{4}-\\d{5}"));
        assertTrue("title should name the indicator + period",
                nce.getTitle().contains("AMENDMENT") && nce.getTitle().contains("2099-01"));
        assertEquals("System (QI monitoring)", nce.getNameOfReporter());
        assertTrue("an AUTO_CREATED history entry should be logged", nceHistoryService.findByNceId(nce.getId()).stream()
                .anyMatch(h -> "AUTO_CREATED".equals(h.getActivity())));
    }

    @Test
    public void createBreachNce_isIdempotentPerIndicatorAndPeriod() {
        NcEvent first = qiBreachNceService.createBreachNce("AMENDMENT", "2099-01", bd("50"), bd("2"), "LOWER_BETTER",
                "%");
        NcEvent second = qiBreachNceService.createBreachNce("AMENDMENT", "2099-01", bd("60"), bd("2"), "LOWER_BETTER",
                "%");
        assertEquals("same indicator+period must reuse the NCE", first.getId(), second.getId());

        NcEvent nextPeriod = qiBreachNceService.createBreachNce("AMENDMENT", "2099-02", bd("50"), bd("2"),
                "LOWER_BETTER", "%");
        assertNotEquals("a new period re-fires a distinct NCE", first.getId(), nextPeriod.getId());
    }

    // ---- evaluator decision path ----

    @Test
    public void evaluate_amendmentDisabled_firesNothing() {
        // Disabled default short-circuits before any compute (711 contract).
        qiConfigService.saveIndicator("AMENDMENT", view(false, bd("0"), bd("2")), USER);
        qiBreachEvaluatorService.evaluateBreaches();
        assertEquals(0, qiBreachCount());
    }

    @Test
    public void evaluate_amendmentBreach_firesOneNcePerPeriod() throws Exception {
        seedAmendmentActivity();
        AmendmentSummaryResponse summary = amendmentReportService.getSummary(LocalDate.now().withDayOfMonth(1),
                LocalDate.now());
        assertNotNull("seed should produce released rows", summary.getRatePercent());
        assertTrue("seed should produce a non-zero amendment rate", summary.getRatePercent() > 0);

        // action below the actual rate → LOWER_BETTER breach; target below action.
        BigDecimal action = BigDecimal.valueOf(summary.getRatePercent() / 2.0);
        qiConfigService.saveIndicator("AMENDMENT", view(true, BigDecimal.ZERO, action), USER);

        qiBreachEvaluatorService.evaluateBreaches();

        NcEvent nce = ncEventService.findByTriggerSource(QI_BREACH, "AMENDMENT:" + CURRENT_PERIOD);
        assertNotNull("a breach in the current period must create an NCE", nce);
        assertEquals(Boolean.TRUE, nce.getAutoGenerated());
        assertEquals(1, qiBreachCount());

        // Re-running the evaluator in the same period must not duplicate.
        qiBreachEvaluatorService.evaluateBreaches();
        assertEquals("idempotent within the period", 1, qiBreachCount());
    }

    @Test
    public void evaluate_amendmentWithinThreshold_firesNothing() throws Exception {
        seedAmendmentActivity();
        // action at 100 (max) → a rate can never exceed it → no breach.
        qiConfigService.saveIndicator("AMENDMENT", view(true, BigDecimal.ZERO, new BigDecimal("100")), USER);
        qiBreachEvaluatorService.evaluateBreaches();
        NcEvent nce = ncEventService.findByTriggerSource(QI_BREACH, "AMENDMENT:" + CURRENT_PERIOD);
        assertNull("a rate within the action threshold must not create an NCE", nce);
    }

    @Test
    public void evaluate_rejectionBreach_firesNce() throws Exception {
        seedRejectionActivity();
        RejectionSummaryResponse summary = rejectionReportService.getSummary(LocalDate.now().withDayOfMonth(1),
                LocalDate.now());
        assertNotNull("seed should produce started rows", summary.getRatePercent());
        assertTrue("seed should produce a non-zero rejection rate", summary.getRatePercent() > 0);

        BigDecimal action = BigDecimal.valueOf(summary.getRatePercent() / 2.0);
        qiConfigService.saveIndicator("REJECTION", view(true, BigDecimal.ZERO, action), USER);

        qiBreachEvaluatorService.evaluateBreaches();

        NcEvent nce = ncEventService.findByTriggerSource(QI_BREACH, "REJECTION:" + CURRENT_PERIOD);
        assertNotNull("a rejection breach in the current period must create an NCE", nce);
        assertEquals(Boolean.TRUE, nce.getAutoGenerated());
        assertTrue("description should carry the % unit", nce.getDescription().contains("%"));
    }

    @Test
    public void evaluate_tatBreach_firesNceWithHoursUnit() throws Exception {
        seedTatActivity();
        TATSummaryResponse summary = tatReportService.getSummary(LocalDate.now().withDayOfMonth(1), LocalDate.now(),
                TATSegment.RECEIPT_TO_VALIDATION, TATCalculationMode.CALENDAR, null, null, null, null, null, null,
                false, null);
        assertNotNull("seed should produce a computable mean TAT", summary.getMean());
        assertTrue("seed should produce a positive mean TAT", summary.getMean().doubleValue() > 0);

        // TAT thresholds are hours, LOWER_BETTER: action below the actual mean
        // → breach; target below action satisfies the ordering validation.
        BigDecimal action = BigDecimal.valueOf(summary.getMean().doubleValue() / 2.0);
        BigDecimal target = BigDecimal.valueOf(summary.getMean().doubleValue() / 4.0);
        qiConfigService.saveIndicator("TAT", view(true, target, action), USER);

        qiBreachEvaluatorService.evaluateBreaches();

        NcEvent nce = ncEventService.findByTriggerSource(QI_BREACH, "TAT:" + CURRENT_PERIOD);
        assertNotNull("a TAT breach in the current period must create an NCE", nce);
        assertTrue("description should carry the hours unit", nce.getDescription().contains("h vs action"));
    }

    @Test
    public void evaluate_callbackBreach_firesNce() throws Exception {
        seedCallbackActivity();
        // Config first: the compute resolves CALLBACK, and setUp wiped qi_config.
        // CALLBACK is HIGHER_BETTER, so target must sit above action.
        qiConfigService.saveIndicator("CALLBACK", view(true, new BigDecimal("100"), new BigDecimal("99")), USER);

        CallbackSummaryResponse summary = criticalCallbackService.getSummary(LocalDate.now().withDayOfMonth(1),
                LocalDate.now());
        assertNotNull("seed should produce a critical result in the window", summary.getCompliancePercent());
        assertTrue("the seeded critical has no callback logged, so compliance must be below 99",
                summary.getCompliancePercent() < 99);

        qiBreachEvaluatorService.evaluateBreaches();

        NcEvent nce = ncEventService.findByTriggerSource(QI_BREACH, "CALLBACK:" + CURRENT_PERIOD);
        assertNotNull("a callback-compliance breach in the current period must create an NCE", nce);
        assertEquals(Boolean.TRUE, nce.getAutoGenerated());
        assertTrue("description should carry the % unit", nce.getDescription().contains("%"));
    }

    @Test
    public void evaluate_callbackAboveActionThreshold_firesNothing() throws Exception {
        seedCallbackActivity();
        // action at 0 → compliance can never fall below it → no breach. Proves the
        // CALLBACK path is threshold-driven rather than firing on every run.
        qiConfigService.saveIndicator("CALLBACK", view(true, new BigDecimal("100"), BigDecimal.ZERO), USER);
        assertNotNull("the metric must be computable, else this asserts nothing", criticalCallbackService
                .getSummary(LocalDate.now().withDayOfMonth(1), LocalDate.now()).getCompliancePercent());

        qiBreachEvaluatorService.evaluateBreaches();

        assertNull("compliance at or above the action threshold must not create an NCE",
                ncEventService.findByTriggerSource(QI_BREACH, "CALLBACK:" + CURRENT_PERIOD));
    }

    @Test
    public void evaluate_oneIndicatorFailing_doesNotSuppressOthers() throws Exception {
        // Only AMENDMENT is configured; REJECTION/TAT resolve() throws (no
        // default row) and must be contained per indicator.
        seedAmendmentActivity();
        AmendmentSummaryResponse summary = amendmentReportService.getSummary(LocalDate.now().withDayOfMonth(1),
                LocalDate.now());
        BigDecimal action = BigDecimal.valueOf(summary.getRatePercent() / 2.0);
        qiConfigService.saveIndicator("AMENDMENT", view(true, BigDecimal.ZERO, action), USER);

        qiBreachEvaluatorService.evaluateBreaches();

        assertNotNull("amendment must still fire despite unconfigured siblings",
                ncEventService.findByTriggerSource(QI_BREACH, "AMENDMENT:" + CURRENT_PERIOD));
    }

    // ---- helpers ----

    /**
     * Reuse the QC dataset's valid analyses: stamp a few as released this month and
     * add one corrected-result note so the amendment rate is non-zero for the
     * current period.
     */
    private void seedAmendmentActivity() throws Exception {
        executeDataSetWithStateManagement("testdata/qc-violation-nce.xml");
        jdbc.update("UPDATE clinlims.analysis SET released_date = now()"
                + " WHERE id IN ('9001','9002','9003','9004','9005')");
        Long analysisRef = Long.valueOf(referenceTablesService.getReferenceTableByName("ANALYSIS").getId());
        jdbc.update("INSERT INTO clinlims.note (id, sys_user_id, reference_id, reference_table, note_type, text,"
                + " lastupdated) VALUES (nextval('clinlims.note_seq'), 1, 9001, ?, 'E', 'Result corrected', now())",
                analysisRef);
    }

    /**
     * Reuse the QC dataset's valid analyses: stamp them as started this month and
     * reject one with an 'R' note so the rejection rate is non-zero for the current
     * period.
     */
    private void seedRejectionActivity() throws Exception {
        executeDataSetWithStateManagement("testdata/qc-violation-nce.xml");
        jdbc.update("UPDATE clinlims.analysis SET started_date = now()"
                + " WHERE id IN ('9001','9002','9003','9004','9005')");
        Long analysisRef = Long.valueOf(referenceTablesService.getReferenceTableByName("ANALYSIS").getId());
        jdbc.update("INSERT INTO clinlims.note (id, sys_user_id, reference_id, reference_table, note_type, text,"
                + " lastupdated) VALUES (nextval('clinlims.note_seq'), 1, 9001, ?, 'R', 'Hemolyzed specimen', now())",
                analysisRef);
    }

    /**
     * Stamp the QC dataset's sample as received this month (clamped to the month
     * start so the test can't straddle a month boundary) and release its analyses
     * now, giving RECEIPT_TO_VALIDATION a positive month-to-date mean.
     */
    private void seedTatActivity() throws Exception {
        executeDataSetWithStateManagement("testdata/qc-violation-nce.xml");
        jdbc.update("UPDATE clinlims.sample SET received_date ="
                + " GREATEST(date_trunc('month', now()), now() - interval '10 hours') WHERE id = 701");
        jdbc.update("UPDATE clinlims.analysis SET released_date = now()"
                + " WHERE id IN ('9001','9002','9003','9004','9005')");
    }

    /**
     * One released critical result this month with no callback logged, so the
     * month-to-date compliance is computable and strictly below 100%. Self-seeded
     * (not from a dataset) because the compute needs a result_limits critical band
     * on the analysis's test, which the shared QC fixture does not carry.
     */
    private void seedCallbackActivity() {
        jdbc.update(
                "INSERT INTO clinlims.test (id, name, description, is_active, guid, lastupdated)"
                        + " VALUES (?, ?, ?, 'Y', ?, NOW())",
                CALLBACK_TEST_ID, "CallbackBreachIT", "CallbackBreachIT desc", UUID.randomUUID().toString());
        jdbc.update(
                "INSERT INTO clinlims.result_limits (id, test_id, test_result_type_id, min_age, max_age,"
                        + " low_critical, high_critical, lastupdated) VALUES (?, ?, 4, 0, ?, 10, 90, NOW())",
                CALLBACK_TEST_ID, CALLBACK_TEST_ID, Double.POSITIVE_INFINITY);
        jdbc.update(
                "INSERT INTO clinlims.sample (id, accession_number, entered_date, received_date, is_confirmation,"
                        + " lastupdated) VALUES (?, ?, NOW(), NOW(), false, NOW())",
                CALLBACK_TEST_ID, "CBBR" + CALLBACK_TEST_ID);
        jdbc.update("INSERT INTO clinlims.sample_item (id, samp_id, sort_order, status_id, lastupdated)"
                + " VALUES (?, ?, 1, 1, NOW())", CALLBACK_TEST_ID, CALLBACK_TEST_ID);
        jdbc.update(
                "INSERT INTO clinlims.analysis (id, analysis_type, test_id, sampitem_id, released_date, lastupdated)"
                        + " VALUES (?, 'MANUAL', ?, ?, now(), NOW())",
                CALLBACK_ANALYSIS_ID, CALLBACK_TEST_ID, CALLBACK_TEST_ID);
        // 98 is outside the 10–90 critical band; no critical_callback row exists
        // for it, so it counts in the denominator only.
        jdbc.update("INSERT INTO clinlims.result (id, analysis_id, value, result_type, lastupdated)"
                + " VALUES (?, ?, '98', 'N', NOW())", CALLBACK_ANALYSIS_ID, CALLBACK_ANALYSIS_ID);
    }

    private void clearCallbackSeed() {
        jdbc.update("DELETE FROM clinlims.critical_callback WHERE analysis_id = ?", CALLBACK_ANALYSIS_ID);
        jdbc.update("DELETE FROM clinlims.result WHERE id = ?", CALLBACK_ANALYSIS_ID);
        jdbc.update("DELETE FROM clinlims.analysis WHERE id = ?", CALLBACK_ANALYSIS_ID);
        jdbc.update("DELETE FROM clinlims.sample_item WHERE id = ?", CALLBACK_TEST_ID);
        jdbc.update("DELETE FROM clinlims.sample WHERE id = ?", CALLBACK_TEST_ID);
        jdbc.update("DELETE FROM clinlims.result_limits WHERE id = ?", CALLBACK_TEST_ID);
        jdbc.update("DELETE FROM clinlims.test WHERE id = ?", CALLBACK_TEST_ID);
    }

    private void clearQiBreachNces() {
        jdbc.update("DELETE FROM clinlims.nce_history WHERE nce_id IN"
                + " (SELECT id FROM clinlims.nc_event WHERE trigger_source_type = ?)", QI_BREACH);
        jdbc.update("DELETE FROM clinlims.nc_event WHERE trigger_source_type = ?", QI_BREACH);
    }

    private int qiBreachCount() {
        return jdbc.queryForObject("SELECT COUNT(*) FROM clinlims.nc_event WHERE trigger_source_type = ?",
                Integer.class, QI_BREACH);
    }

    private static BigDecimal bd(String s) {
        return new BigDecimal(s);
    }

    private static QiConfigView view(boolean enabled, BigDecimal target, BigDecimal action) {
        QiConfigView v = new QiConfigView();
        v.setEnabled(enabled);
        v.setTarget(target);
        v.setAction(action);
        return v;
    }
}
