update clinlims.test set orderable=false where name in 
('Acide nalidixique 30 μg',
'Acide fusidique 10 μg',
'Amikacine 30 μg',
'Ampicilline 10 μg',
'Ampicilline/Sulbactam 10/10 μg',
'Amoxicilline/Acide clavulanique 20/10 μg',
'Azithromicine 15 μg',
'Aztreinam 30 μg',
'Cefalotine 30 μg',
'Cefotaxime 30 μg',
'Ceftazidime 30 μg',
'Ceftriaxone 30 μg',
'Cefixime10 μg',
'Ceftizoxime 30 μg',
'Chloramfenicol 30 μg',
'Ciprofloxacine 5 μg',
'Colistine 50 μg',
'Enoxacine 50 μg',
'Erythromycine 15 UI',
'Fosfomycine 50 μg',
'Gentamicine 15 μg',
'Lincomycine 15 μg',
'Levofloxacine 5 μg',
'Lomefloxacine 5 μg',
'Mecillinam 10 μg',
'Meropeneme 10 μg',
'Moxalactam',
'Moxifloxacine 5 μg',
'Nitrofuranes 300 μg',
'Norfloxacine 5 μg',
'Oxacilline 1 μg',
'Oxacilline 5 μg',
'Ofloxacine 5 μg',
'Pefloxacine 5 μg',
'Penicilline G 6 μg (10 UI)',
'Piperacilline 75 μg',
'Pristinamycine 15 μg',
'Quinupristine- Dalfopristine 15 μg',
'Rifampicine 30 μg',
'Sparfloxacine 5 μg',
'Sulfamethoxazole /Trimethroprime23.75 /1,25 μg',
'Teiclopanine 30 μg',
'Tetracycline 30 UI',
'Ticarcilline 75 μg',
'Tobramycine 10 μg');
