INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='UI/L') , 'Transaminases GPT (37°C)(Serum)' , 'TGP' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Biochemistry' ) ,'Transaminases GPT (3' ,10 , 'Transaminases GPT (37°C)' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='UI/L') , 'Transaminases G0T (37°C)(Serum)' , 'TGO' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Biochemistry' ) ,'Transaminases G0T (3' ,20 , 'Transaminases G0T (37°C)' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='g/l') , 'Glucose(Plasma)' , 'Glycémie' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Biochemistry' ) ,'Glucose' ,30 , 'Glucose' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='mg/l') , 'Créatinine(Serum)' , 'Creatinine' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Biochemistry' ) ,'Créatinine' ,40 , 'Créatinine' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='UI/L') , 'Amylase(Serum)' , 'Amylase' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Biochemistry' ) ,'Amylase' ,50 , 'Amylase' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='g/l') , 'Albumine recherche miction(Urines)' , 'Albumine' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Biochemistry' ) ,'Albumine recherche m' ,60 , 'Albumine recherche miction' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='g/l') , 'Cholestérol total(Serum)' , 'Chol total' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Biochemistry' ) ,'Cholestérol total' ,70 , 'Cholestérol total' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='g/l') , 'Cholestérol HDL(Serum)' , 'Chol HDL' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Biochemistry' ) ,'Cholestérol HDL' ,80 , 'Cholestérol HDL' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='g/l') , 'Triglycérides(Serum)' , 'Triglycérides' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Biochemistry' ) ,'Triglycérides' ,90 , 'Triglycérides' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='g/l') , 'Prolans (BHCG) urines de 24 h(Urines)' , 'Béta HCG – 24 h' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Biochemistry' ) ,'Prolans (BHCG) urine' ,100 , 'Prolans (BHCG) urines de 24 h' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'Test urinaire de grossesse(Urine)' , 'Test Grossesse' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Biochemistry' ) ,'Test urinaire de gro' ,110 , 'Test urinaire de grossesse' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'Protéinurie sur bandelette(Urine)' , 'Protéines' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Biochemistry' ) ,'Protéinurie sur ban' ,120 , 'Protéinurie sur bandelette' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='mille/mm3') , 'Numération des globules blancs(Sang total)' , 'GB' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Numération des glob' ,130 , 'Numération des globules blancs' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='million/mm3') , 'Numération des globules rouges(Sang total)' , 'GR' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Numération des glob' ,140 , 'Numération des globules rouges' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='g/dl') , 'Hémoglobine(Sang total)' , 'Hb' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Hémoglobine' ,150 , 'Hémoglobine' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='%') , 'Hémotocrite(Sang total)' , 'Hte' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Hémotocrite' ,160 , 'Hémotocrite' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='fl') , 'Volume Globulaire Moyen(Sang total)' , 'VGM' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Volume Globulaire Mo' ,170 , 'Volume Globulaire Moyen' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='pg') , 'Teneur Corpusculaire Moyenne en Hémoglobine(Sang total)' , 'TCMH' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Teneur Corpusculaire' ,180 , 'Teneur Corpusculaire Moyenne en Hémoglobine' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='%') , 'Concentration Corpusculaire Moyenne en Hémoglobine(Sang total)' , 'CCMH' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Concentration Corpus' ,190 , 'Concentration Corpusculaire Moyenne en Hémoglobine' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='mille/mm3') , 'Plaquette(Sang total)' , 'Plaquettes' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Plaquette' ,200 , 'Plaquette' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='%') , 'Polynucléaires Neutrophiles (%)(Sang total)' , 'PNN %' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Polynucléaires Neut' ,210 , 'Polynucléaires Neutrophiles (%)' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='/mm3') , 'Polynucléaires Neutrophiles (Abs)(Sang total)' , 'PNN (Abs)' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Polynucléaires Neut' ,220 , 'Polynucléaires Neutrophiles (Abs)' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='%') , 'Polynucléaires Eosinophiles (%)(Sang total)' , 'PNE (%)' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Polynucléaires Eosi' ,230 , 'Polynucléaires Eosinophiles (%)' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='/mm3') , 'Polynucléaires Eosinophiles (Abs)(Sang total)' , 'PNE (Abs)' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Polynucléaires Eosi' ,240 , 'Polynucléaires Eosinophiles (Abs)' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='%') , 'Polynucléaires basophiles (%)(Sang total)' , 'PNB (%)' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Polynucléaires baso' ,250 , 'Polynucléaires basophiles (%)' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='/mm3') , 'Polynucléaires basophiles (Abs)(Sang total)' , 'PNB (Abs)' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Polynucléaires baso' ,260 , 'Polynucléaires basophiles (Abs)' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='%') , 'Lymphocytes (%)(Sang total)' , 'Lympho (%)' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Lymphocytes (%)' ,270 , 'Lymphocytes (%)' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='/mm3') , 'Lymphocytes (Abs)(Sang total)' , 'Lympho (Abs)' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Lymphocytes (Abs)' ,280 , 'Lymphocytes (Abs)' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='%') , 'Monocytes (%)(Sang total)' , 'Mono (%)' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Monocytes (%)' ,290 , 'Monocytes (%)' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='/mm3') , 'Monocytes (Abs)(Sang total)' , 'Mono (Abs)' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Hematology' ) ,'Monocytes (Abs)' ,300 , 'Monocytes (Abs)' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'Test rapide HIV 1 + HIV 2(Serum)' , 'VIH rapide-Serum' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'Test rapide HIV 1 + ' ,310 , 'Test rapide HIV 1 + HIV 2' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'Test rapide HIV 1 + HIV 2(Plasma)' , 'VIH rapide-Plasm' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'Test rapide HIV 1 + ' ,320 , 'Test rapide HIV 1 + HIV 2' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'Test rapide HIV 1 + HIV 2(Sang total)' , 'VIH rapide-SangT' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'Test rapide HIV 1 + ' ,330 , 'Test rapide HIV 1 + HIV 2' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='mm3') , 'Dénombrement des lymphocytes CD4 (mm3)(Sang total)' , 'CD4  (Abs)' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Immunology' ) ,'Dénombrement des ly' ,340 , 'Dénombrement des lymphocytes CD4 (mm3)' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='%') , 'Dénombrement des lymphocytes  CD4 (%)(Sang total)' , 'CD4 %' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Immunology' ) ,'Dénombrement des ly' ,350 , 'Dénombrement des lymphocytes  CD4 (%)' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'HBs AG (antigén australia)(Serum)' , 'Ag HBs' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'HBs AG (antigén aus' ,360 , 'HBs AG (antigén australia)' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='copies/ml') , 'Mesure de la charge virale(Sang total)' , 'Charge virale VIH' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Biologie Moleculaire' ) ,'Mesure de la charge ' ,370 , 'Mesure de la charge virale' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='copies/ml') , 'Detection de la resistance aux antiretroviraux(Sang total)' , 'ARV res' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Biologie Moleculaire' ) ,'Detection de la resi' ,380 , 'Detection de la resistance aux antiretroviraux' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'Western blot VIH(Serum)' , 'WB-Serum' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'Western blot VIH' ,390 , 'Western blot VIH' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'Western blot VIH(Plasma)' , 'WB-Plasma' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'Western blot VIH' ,400 , 'Western blot VIH' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'Bioline(Plasma)' , 'Bioline-Plasma' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'Bioline' ,410 , 'Bioline' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'Bioline(Serum)' , 'Bioline-Serum' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'Bioline' ,420 , 'Bioline' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'Bioline(Sang total)' , 'Bioline-Sang total' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'Bioline' ,430 , 'Bioline' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'Genie III(Plasma)' , 'Genie III-Plasma' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'Genie III' ,440 , 'Genie III' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'Genie III(Serum)' , 'Genie III-Serum' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'Genie III' ,450 , 'Genie III' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'Genie III(Sang total)' , 'Genie III-Sang t' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'Genie III' ,460 , 'Genie III' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'Murex(Plasma)' , 'Murex-Plasma' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'Murex' ,470 , 'Murex' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'Murex(Serum)' , 'Murex-Serum' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'Murex' ,480 , 'Murex' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'Vironostika(Plasma)' , 'Vironostika-Plas' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'Vironostika' ,490 , 'Vironostika' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'Vironostika(Serum)' , 'Vironostika-Seru' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'Vironostika' ,500 , 'Vironostika' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'P24 Ag(Plasma)' , 'P24 Ag-Plasma' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'P24 Ag' ,510 , 'P24 Ag' );
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name )
	VALUES ( nextval( 'test_seq' ) , null , 'P24 Ag(Serum)' , 'P24 Ag-Serum' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Serology-Immunology' ) ,'P24 Ag' ,520 , 'P24 Ag' );
