# build env
FROM node:19.2-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm ci --force
COPY . ./
RUN npm run build

# production env
FROM nginx:1.15-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY --from=build /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]