update clinlims.dictionary set dict_entry = 'Positive pour Vibrio cholera O1 Ogawa' where dict_entry = 'Antibiogramme pour Vibrio cholera O1 Ogawa' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Positive pour Vibrio cholera O1 Inaba' where dict_entry = 'Antibiogramme pour Vibrio cholera O1 Inaba' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Positive pour Vibrio cholera O139' where dict_entry = 'Antibiogramme pour Vibrio cholera O139' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Positive pour Vibrio cholera O1' where dict_entry = 'Antibiogramme pour Vibrio cholera O1' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Positive pour Vibrio cholera Non-O1' where dict_entry = 'Antibiogramme pour Vibrio cholera Non-O1' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Positive pour Samonella Typhi' where dict_entry = 'Antibiogramme pour Samonella Typhi' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Positive pour Samonella Enterica' where dict_entry = 'Antibiogramme pour Samonella Enterica' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Positive pour Samonella sp.' where dict_entry = 'Antibiogramme pour Samonella sp.' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Positive pour Shigella flexneri' where dict_entry = 'Antibiogramme pour Shigella flexneri' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Positive pour Shigella boydii' where dict_entry = 'Antibiogramme pour Shigella boydii' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Positive pour Shigella sonnei' where dict_entry = 'Antibiogramme pour Shigella sonnei' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Positive pour Shigella dysenteriae'  where dict_entry = 'Antibiogramme pour Shigella dysenteriae' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');

