INSERT INTO clinlims.test( id,  uom_id, description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, reporting_description )
VALUES ( nextval( 'test_seq' ) ,
         null ,
         'Examen Microscopique(Selles)' ,
         'Y' ,
         'N' ,
         now() ,
         (select id from clinlims.test_section where name = 'Parasitology' ) ,
         'Examen Microscopique' ,
         37650 ,
         'Examen Microscopique' ,
         null,
         'Examen Microscopique' );

INSERT INTO clinlims.sampletype_test (id, test_id , sample_type_id) VALUES
  (nextval( 'sample_type_test_seq' ) , (select id from test where description = 'Examen Microscopique(Selles)' )  ,
   (select id from type_of_sample where description = 'Selles')  );

INSERT INTO clinlims.dictionary(  id, is_active, dict_entry, lastupdated, dictionary_category_id, sort_order)
VALUES ( nextval( 'dictionary_seq' ) , 'Y','Pas d''evidence de parasite' , now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 107400),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Entamoeba histolotica', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 107400),
  ( nextval( 'dictionary_seq' ) , 'Y','Entamoeba coli' , now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 107400),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Entamoeba hartmani', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 107500),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Endolimax nana', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 107600),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Pseudolimax (lodamoeba) butschlii', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 107700),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Giardia intestinalis', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 107800),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Trichomonas hominis', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 107900),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Chilomastix mesnili', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 108000),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Enteromonas hominis', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 108100),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Embadomonas instestinalis', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 108200),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Ascaris lumbricoides', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 108300),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Enterobius vermicularis', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 108400),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Ankylostoma duodenale/ Necator americanus (Ankylostomes)', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 108500),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Strongyloides stercoralis (Anguillule)', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 108600),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Taenia saginata/Taenia solium', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 108700),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Hymenolepis diminuta', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 108800),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Cytosisospora', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 108900),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Kystes', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 109000),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Trophozoites', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 109100),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Oeufs', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 109200),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Larves', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 109300),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Adultes', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 109400),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Peu (? 2)', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 109500),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Modere (3-9)', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 109600),
  ( nextval( 'dictionary_seq' ) , 'Y', 'Beaucoup (? 10)', now() , (select id from clinlims.dictionary_category where description = 'Haiti Lab'), 109700);

INSERT INTO clinlims.test_result( id, test_id, tst_rslt_type, value , lastupdated, sort_order, is_quantifiable)
VALUES ( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
         'C' ,  ( select max(id) from clinlims.dictionary where dict_entry ='Pas d''evidence de parasite' )  , now() , 10, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Entamoeba histolotica'  )  , now() , 20, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Entamoeba coli'  )  , now() , 30, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Entamoeba hartmani' )  , now() , 40, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Endolimax nana' )  , now() , 50, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Pseudolimax (lodamoeba) butschlii'  )  , now() , 60, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Giardia intestinalis' )  , now() , 70, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Trichomonas hominis' )  , now() , 80, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Chilomastix mesnili' )  , now() , 90, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
  'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Enteromonas hominis' )  , now() , 100, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
  'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Embadomonas instestinalis' )  , now() , 110, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
  'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Trichuris trichiura' )  , now() , 120, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
  'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Ascaris lumbricoides' )  , now() , 130, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
  'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Enterobius vermicularis' )  , now() , 140, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
  'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Ankylostoma duodenale/ Necator americanus (Ankylostomes)' )  , now() , 150, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
  'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Strongyloides stercoralis (Anguillule)' )  , now() , 160, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
  'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Taenia saginata/Taenia solium' )  , now() , 170, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
  'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Hymenolepis nana' )  , now() , 180, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
  'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Hymenolepis diminuta' )  , now() , 190, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Cryptosporidium' )  , now() , 200, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Cyclospora' )  , now() , 210, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Cytosisospora' )  , now() , 220, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Sarcocystis' )  , now() , 230, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Autre' )  , now() , 240, true),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Kystes' )  , now() , 250, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Trophozoites' )  , now() , 260, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Oeufs' )  , now() , 270, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
  'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Larves' )  , now() , 280, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
  'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Adultes' )  , now() , 290, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
  'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Peu (? 2)' )  , now() , 300, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
  'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Modere (3-9)' )  , now() , 310, false),
( nextval( 'test_result_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) ,
  'C' ,  ( select max(id) from clinlims.dictionary where dict_entry = 'Beaucoup (? 10)' )  , now() , 320, false);


INSERT INTO result_limits(  id, test_id, test_result_type_id, min_age, max_age, gender, low_normal, high_normal, low_valid, high_valid, lastupdated, normal_dictionary_id )
VALUES ( nextval( 'result_limits_seq' ) , ( select id from clinlims.test where description = 'Examen Microscopique(Selles)' ) , (select id from clinlims.type_of_test_result where test_result_type = 'C' ) ,
         0, 'Infinity' , '' ,0,100,0,100, now(), ( select max(id) from clinlims.dictionary where dict_entry = 'Pas d''evidence de parasite' ) );

INSERT INTO panel_item( id, panel_id, lastupdated , test_id)
VALUES ( nextval( 'panel_item_seq' ) , (select id from panel where name = 'Selles Routine') , now(), (select id from test where description = 'Examen Microscopique(Selles)' and is_active = 'Y' ) );
