
update clinlims.dictionary set dict_entry = 'Antibiogramme pour Vibrio cholera O1 Ogawa', local_abbrev = 'Vibrio cholera O1 Ogawa' where dict_entry = 'Positive pour Vibro cholerae O1 Ogawa' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Antibiogramme pour Vibrio cholera O1 Inaba', local_abbrev = 'Vibrio cholera O1 Inaba' where dict_entry = 'Positive pour Vibro cholerae O1 Inaba' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Antibiogramme pour Vibrio cholera O139', local_abbrev = 'Vibrio cholera O139' where dict_entry = 'Positive pour Vibro cholerae O139' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Antibiogramme pour Vibrio cholera O1', local_abbrev = 'Vibrio cholera O1' where dict_entry = 'Positive pour Vibro cholerae O1' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Antibiogramme pour Vibrio cholera Non-O1', local_abbrev = 'Vibrio cholera Non-O1' where dict_entry = 'Positive pour Vibro cholerae Non-O1' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Antibiogramme pour Samonella Typhi', local_abbrev = 'Samonella Typhi' where dict_entry = 'Positive pour Samonella Typhi' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Antibiogramme pour Samonella Enterica', local_abbrev = 'Samonella Enterica' where dict_entry = 'Positive pour Samonella Enterica' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Antibiogramme pour Samonella sp.', local_abbrev = 'Samonella sp.' where dict_entry = 'Positive pour Samonella sp.' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Antibiogramme pour Shigella flexneri', local_abbrev = 'Shigella flexneri' where dict_entry = 'Positive pour Shigella flexneri' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Antibiogramme pour Shigella boydii', local_abbrev = 'Shigella boydii' where dict_entry = 'Positive pour Shigella boydii' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Antibiogramme pour Shigella sonnei', local_abbrev = 'Shigella sonnei' where dict_entry = 'Positive pour Shigella sonnei' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');
update clinlims.dictionary set dict_entry = 'Antibiogramme pour Shigella dysenteriae', local_abbrev = 'Shigella dysenteriae' where dict_entry = 'Positive pour Shigella dysenteriae' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'posBact');

update clinlims.dictionary set dict_entry = 'Négative pour Vibrio cholera O1 Ogawa, Salmonella et Shigella' where dict_entry = 'Negative pour Vibro chlorea O1 Ogawa, Salmonella et Shigella' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'negBact');
update clinlims.dictionary set dict_entry = 'Négative pour Salmonella et Shigella' where dict_entry = 'Negative pour Salmonella et Shigella' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'negBact');
update clinlims.dictionary set dict_entry = 'Négative pour Salmonella, Salmonella et Shigella' where dict_entry = 'Negative pour Salmonella' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'negBact');
update clinlims.dictionary set dict_entry = 'Négative pour Shigella' where dict_entry = 'Negative pour Shigella' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'negBact');
update clinlims.dictionary set dict_entry = 'Négative pour Vibrio cholera O1 Ogawa' where dict_entry = 'Negative pour Vibro cholerae O1 Ogawa' and dictionary_category_id = (select id from clinlims.dictionary_category where local_abbrev = 'negBact');


