INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Goutte épaisse(Sang total)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Malaria' ) ,'Goutte épaisse' ,610 , 'Goutte épaisse' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='trophzoïtes/µl de sang') , 'Parasitémie(Sang total)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Malaria' ) ,'Parasitémie' ,620 , 'Parasitémie' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Frottis Mince(Sang total)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Malaria' ) ,'Frottis Mince' ,630 , 'Frottis Mince' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Autres espèces(Sang total)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Malaria' ) ,'Autres espèces' ,640 , 'Autres espèces' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Scotch test anal(Scotch Test Anal)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Scotch test anal' ,650 , 'Scotch test anal' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Aspect des selles(Selles)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Aspect des selles' ,660 , 'Aspect des selles' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Parasites(Selles)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Parasites' ,670 , 'Parasites' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Eléments fongiques(Selles)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Eléments fongiques' ,680 , 'Eléments fongiques' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Concentration des selles(Selles)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Concentration des se' ,690 , 'Concentration des selles' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Baermann(Selles)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Baermann' ,700 , 'Baermann' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Ziehl neelsen(Selles)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Ziehl neelsen' ,710 , 'Ziehl neelsen' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Coproculture(Selles)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Coproculture' ,720 , 'Coproculture' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'IgM(Sérum)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'IgM' ,730 , 'IgM' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='µl/ml') , 'Index IgM(Sérum)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Index IgM' ,740 , 'Index IgM' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'IgG(Sérum)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'IgG' ,750 , 'IgG' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='µl/ml') , 'Titre IgG(Sérum)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Titre IgG' ,760 , 'Titre IgG' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'HAI amibiase(Sérum)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'HAI amibiase' ,770 , 'HAI amibiase' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='µl/ml') , 'Titre Ac anti-amibien (BERHING)(Sérum)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Titre Ac anti-amibie' ,780 , 'Titre Ac anti-amibien (BERHING)' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='µl/ml') , 'Titre Ac anti-amibien (FUMOUZE)(Sérum)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Titre Ac anti-amibie' ,790 , 'Titre Ac anti-amibien (FUMOUZE)' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Résultat HAI bilharziose(Sérum)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Résultat HAI bilhar' ,800 , 'Résultat HAI bilharziose' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='µl/ml') , 'Titre Ac antibilharzien (BERHING)(Sérum)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Titre Ac antibilharz' ,810 , 'Titre Ac antibilharzien (BERHING)' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , ( select id from clinlims.unit_of_measure where name='µl/ml') , 'Titre Ac antibilharzien (FUMOUZE)(Sérum)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Titre Ac antibilharz' ,820 , 'Titre Ac antibilharzien (FUMOUZE)' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Aspect des urines(Urines)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Aspect des urines' ,830 , 'Aspect des urines' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Parasites (examen direct)(Urines)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Parasites (examen di' ,840 , 'Parasites (examen direct)' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Eléments fongiques (examen direct)(Urines)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Eléments fongiques ' ,850 , 'Eléments fongiques (examen direct)' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Parasites (après centrifugation)(Urines)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Parasites (après ce' ,860 , 'Parasites (après centrifugation)' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Recherche de microfilaires' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Recherche de microfi' ,870 , 'Recherche de microfilaires' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Recherche de leishmanies' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'Parasitology' ) ,'Recherche de leishma' ,880 , 'Recherche de leishmanies' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Scotch test cutane(Biopsie)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Scotch test cutane' ,890 , 'Scotch test cutane' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Filaments - mycoses profondes' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Filaments - mycoses profondes' ,900 , 'Filaments - mycoses profondes' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Filaments - mycose superficielle' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Filaments - mycose superficielle' ,1120 , 'Filaments - mycose superficielle' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Leucocytes' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Leucocytes' ,920 , 'Leucocytes' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Test encre chine(LCR)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Test encre chine' ,930 , 'Test encre chine' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Hématies' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Hématies' ,940 , 'Hématies' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Parasites - mycoses superficielles' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Parasites - mycoses superficielles' ,1160 , 'Parasites - mycoses superficielles' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Parasites - mycoses profondes' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Parasites - mycoses profondes' ,950 , 'Parasites - mycoses profondes' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Sur milieu Sc' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Sur milieu Sc' ,960 , 'Sur milieu Sc' , '', true);	
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Sur milieu SAC  - mycoses profondes' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Sur milieu SAC  - mycoses profondes' ,1190 , 'Sur milieu SAC  - mycoses profondes' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Sur milieu SAC  - mycose superficielle' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Sur milieu SAC  - mycose superficielle' ,970 , 'Sur milieu SAC  - mycose superficielle' , '', true);	
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Test ag soluble(LCR)' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Test ag soluble' ,990 , 'Test ag soluble' , '', false);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Germe isolé antifongigramme' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Germe isolé antifon' ,1000 , 'Germe isolé antifongigramme' , '', false);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Flucytosine 1 ug' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Flucytosine 1 ug' ,1010 , 'Flucytosine 1 ug' , '', false);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Flucytosine 10 ug' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Flucytosine 10 ug' ,1020 , 'Flucytosine 10 ug' , '', false);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Amphotéricine B' , 'AB' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Amphotéricine B' ,1030 , 'Amphotéricine B' , '', false);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Fluconazole' , 'FLU' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Fluconazole' ,1040 , 'Fluconazole' , '', false);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Miconazole' , 'MCZ' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Miconazole' ,1050 , 'Miconazole' , '', false);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Econazole' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Econazole' ,1060 , 'Econazole' , '', false);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Kétéconazole' , 'KET' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Kétéconazole' ,1070 , 'Kétéconazole' , '', false);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Nystatine' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Nystatine' ,1080 , 'Nystatine' , '', false);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Voriconazole' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Voriconazole' ,1090 , 'Voriconazole' , '', false);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Itraconazole' , 'ITR' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Itraconazole' ,1100 , 'Itraconazole' , '', false);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Clotrimazole' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Clotrimazole' ,1110 , 'Clotrimazole' , '', false);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Germe isolé mycose profonde' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Germe isolé mycose ' ,980 , 'Germe isolé mycose profonde' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Grains' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Grains' ,1140 , 'Grains' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Spores' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Spores' ,1150 , 'Spores' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Attaque pilaire' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Attaque pilaire' ,1170 , 'Attaque pilaire' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Sur milieu SC' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Sur milieu SC' ,1180 , 'Sur milieu SC' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Sur milieu taplin' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Sur milieu taplin' ,1200 , 'Sur milieu taplin' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Levure mycose superficielle' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Levure mycose superf' ,1130 , 'Levure mycose superficielle' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Levure mycose profonde' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Levure mycose profon' ,910 , 'Levure mycose profonde' , '', true);
INSERT INTO test( id,  uom_id, description, reporting_description, is_active, is_reportable, lastupdated, test_section_id, local_abbrev, sort_order, name, loinc, orderable )
	VALUES ( nextval( 'test_seq' ) , null , 'Germe isolé mycose superficielle' , '' , 'Y' , 'N' , now() , (select id from clinlims.test_section where name = 'mycology' ) ,'Germe isolé mycose ' ,1210 , 'Germe isolé mycose superficielle' , '', false);
