UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Dénombrement des lymphocytes CD4 (mm3)(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Dénombrement des lymphocytes  CD4 (%)(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Transaminases GPT (37°C)(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Transaminases(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Glucose(Plasma)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Glucose(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Créatinine(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Amylase(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Albumine recherche miction(Urines)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Cholestérol total(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Cholestérol HDL(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Triglycérides(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Mesure de la charge virale(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Prolans (BHCG) urines de 24 h(Urines)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Numération des globules blancs(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Numération des globules rouges(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Hémoglobine(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Hémotocrite(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Volume Globulaire Moyen(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Teneur Corpusculaire Moyenne en Hémoglobine(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Concentration Corpusculaire Moyenne en Hémoglobine(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Plaquette(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Polynucléaires Neutrophiles (%)(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Polynucléaires Neutrophiles (Abs)(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Polynucléaires Eosinophiles (%)(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Polynucléaires Eosinophiles (Abs)(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Polynucléaires basophiles (%)(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Polynucléaires basophiles (Abs)(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Lymphocytes (%)(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Lymphocytes (Abs)(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Monocytes (%)(Sang total)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Monocytes (Abs)(Sang total)');
