// T-13 phase-1 fixtures. Field names mirror the frozen cycle contract
// (GET /rest/eqa/cycles/mine, PR #4070): id, cycleNumber, cycleName, status,
// schemeId, plannedStartDate, plannedEndDate, participantState — plus the
// display fields the endpoint does not serve yet (schemeName, provider,
// schemeType, progress, samples, flags). Statuses use the enum names
// lower-cased, exactly as cyclesApi normalizes the real DTO.
export const MOCK_CYCLES = [
  {
    id: 1,
    cycleNumber: "Cycle 2026-02",
    cycleName: "WHO AFRO HIV VL 2026-02",
    status: "TESTING",
    participantState: "TESTING",
    schemeId: 1,
    schemeName: "WHO AFRO HIV Viral Load EQA",
    schemeType: "international_pt",
    provider: "WHO AFRO",
    plannedStartDate: "2026-03-01",
    plannedEndDate: "2026-05-02",
    progress: { entered: 3, total: 5 },
    perAnalyst: false,
    requiresCycleReview: false,
    hasNce: false,
    samples: [
      {
        id: "WHO-HIV-01",
        labNo: "2026-00018421",
        entryStatus: "entered",
        analytes: [{ name: "HIV-1 Viral Load" }],
      },
      {
        id: "WHO-HIV-02",
        labNo: "2026-00018422",
        entryStatus: "in_progress",
        analytes: [{ name: "HIV-1 Viral Load" }],
      },
      {
        id: "WHO-HIV-03",
        labNo: "2026-00018423",
        entryStatus: "entered",
        analytes: [{ name: "HIV-1 Viral Load" }],
      },
      {
        id: "WHO-HIV-04",
        labNo: "2026-00018424",
        entryStatus: "entered",
        analytes: [{ name: "HIV-1 Viral Load" }],
      },
      {
        id: "WHO-HIV-05",
        labNo: "2026-00018425",
        entryStatus: "empty",
        analytes: [{ name: "HIV-1 Viral Load" }],
      },
    ],
  },
  {
    id: 2,
    cycleNumber: "Round 14",
    cycleName: "NHRL TB GeneXpert Round 14",
    status: "READY_TO_SUBMIT",
    participantState: "READY_TO_SUBMIT",
    schemeId: 2,
    schemeName: "NHRL TB GeneXpert PT",
    schemeType: "regional_pt",
    provider: "NHRL Kenya",
    plannedStartDate: "2026-02-15",
    plannedEndDate: "2026-04-28",
    progress: { entered: 6, total: 6 },
    perAnalyst: true,
    requiresCycleReview: true,
    hasNce: false,
    samples: [
      {
        id: "NHRL-TB-01",
        labNo: "2026-00018501",
        entryStatus: "entered",
        analytes: [
          {
            name: "MTB Detection",
            value: "Detected",
            validatedAt: "2026-04-22 14:08:00.0",
          },
          {
            name: "RIF Resistance",
            value: "Not detected",
            validatedAt: "2026-04-22 14:09:00.0",
          },
        ],
        analyst: "J. Otieno",
      },
      {
        id: "NHRL-TB-02",
        labNo: "2026-00018502",
        entryStatus: "entered",
        analytes: [
          {
            name: "MTB Detection",
            value: "Detected",
            validatedAt: "2026-04-22 14:08:00.0",
          },
          {
            name: "RIF Resistance",
            value: "Not detected",
            validatedAt: "2026-04-22 14:09:00.0",
          },
        ],
        analyst: "A. Kamau",
      },
      {
        id: "NHRL-TB-03",
        labNo: "2026-00018503",
        entryStatus: "entered",
        analytes: [
          {
            name: "MTB Detection",
            value: "Detected",
            validatedAt: "2026-04-22 14:08:00.0",
          },
          {
            name: "RIF Resistance",
            value: "Not detected",
            validatedAt: "2026-04-22 14:09:00.0",
          },
        ],
        analyst: "J. Otieno",
      },
    ],
  },
  {
    id: 3,
    cycleNumber: "Cycle 2026-01",
    cycleName: "NTRL Malaria Microscopy 2026-01",
    status: "SCORED",
    participantState: "SCORED",
    schemeId: 3,
    schemeName: "NTRL Malaria Microscopy",
    schemeType: "regional_pt",
    provider: "NTRL",
    plannedStartDate: "2026-01-10",
    plannedEndDate: "2026-03-15",
    progress: { entered: 10, total: 10 },
    perAnalyst: true,
    requiresCycleReview: false,
    hasNce: true,
    nceRef: "NCE-2026-042",
    samples: [],
  },
  {
    id: 4,
    cycleNumber: "Q2 2026",
    cycleName: "In-House CD4 Cross-Bench Q2",
    status: "SUBMITTED",
    participantState: "SUBMITTED",
    schemeId: 4,
    schemeName: "In-House CD4 Cross-Bench",
    schemeType: "in_house",
    provider: "INTERNAL",
    plannedStartDate: "2026-04-01",
    plannedEndDate: "2026-04-20",
    progress: { entered: 4, total: 4 },
    perAnalyst: true,
    requiresCycleReview: false,
    hasNce: false,
    samples: [],
  },
  {
    id: 5,
    cycleNumber: "Cycle 2026-02",
    cycleName: "NMCP Malaria RDT 2026-02",
    status: "PLANNED",
    participantState: "PLANNED",
    schemeId: 5,
    schemeName: "NMCP Malaria RDT PT",
    schemeType: "international_pt",
    provider: "NMCP",
    plannedStartDate: "2026-05-15",
    plannedEndDate: "2026-06-10",
    progress: { entered: 0, total: 8 },
    perAnalyst: false,
    requiresCycleReview: false,
    hasNce: false,
    samples: [],
  },
  {
    id: 6,
    cycleNumber: "Cycle 2026-02",
    cycleName: "CDC HIV Serology 2026-02",
    status: "PANEL_RECEIVED",
    participantState: "PANEL_RECEIVED",
    schemeId: 6,
    schemeName: "CDC HIV Serology PT",
    schemeType: "international_pt",
    provider: "CDC",
    plannedStartDate: "2026-04-10",
    plannedEndDate: "2026-05-20",
    progress: { entered: 0, total: 6 },
    perAnalyst: false,
    requiresCycleReview: false,
    hasNce: false,
    samples: [],
  },
  {
    id: 7,
    cycleNumber: "Round 13",
    cycleName: "NHRL TB GeneXpert Round 13",
    status: "CLOSED",
    participantState: "CLOSED",
    schemeId: 2,
    schemeName: "NHRL TB GeneXpert PT",
    schemeType: "regional_pt",
    provider: "NHRL Kenya",
    plannedStartDate: "2025-11-20",
    plannedEndDate: "2026-01-20",
    progress: { entered: 6, total: 6 },
    perAnalyst: true,
    requiresCycleReview: true,
    hasNce: false,
    samples: [],
  },
  {
    id: 8,
    cycleNumber: "Cycle 2025-06",
    cycleName: "WHO AFRO HIV VL 2025-06",
    status: "SCORED",
    participantState: "SCORED",
    schemeId: 1,
    schemeName: "WHO AFRO HIV Viral Load EQA",
    schemeType: "international_pt",
    provider: "WHO AFRO",
    plannedStartDate: "2025-05-10",
    plannedEndDate: "2025-07-15",
    progress: { entered: 5, total: 5 },
    perAnalyst: false,
    requiresCycleReview: false,
    hasNce: false,
    samples: [],
  },
];
