package org.openelisglobal.qaevent.valueholder;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import java.sql.Date;
import java.util.Objects;
import org.openelisglobal.common.valueholder.BaseObject;

@Entity
@Table(name = "nc_event", schema = "clinlims")
public class NcEvent extends BaseObject<Integer> {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "nc_event_seq_gen")
    @SequenceGenerator(name = "nc_event_seq_gen", sequenceName = "nc_event_id_seq", schema = "clinlims", allocationSize = 1)
    @Column(name = "id")
    private Integer id;

    @Column(name = "report_date")
    private Date reportDate;

    @Column(name = "name", length = 200)
    private String name;

    @Column(name = "title", length = 200)
    private String title;

    @Column(name = "immediate_action")
    private String immediateAction;

    @Column(name = "name_of_reporter", length = 200)
    private String nameOfReporter;

    @Column(name = "nce_number", length = 20)
    private String nceNumber;

    @Column(name = "date_of_event")
    private Date dateOfEvent;

    @Column(name = "lab_order_number", length = 30)
    private String labOrderNumber;

    @Column(name = "prescriber_name", length = 200)
    private String prescriberName;

    @Column(name = "site", length = 200)
    private String site;

    @Column(name = "reporting_unit_id")
    private Integer reportingUnitId;

    @Column(name = "description")
    private String description;

    @Column(name = "suspected_causes")
    private String suspectedCauses;

    @Column(name = "proposed_action")
    private String proposedAction;

    @Column(name = "laboratory_component", length = 10)
    private String laboratoryComponent;

    @Column(name = "consequence_id", length = 10)
    private String consequenceId;

    @Column(name = "recurrence_id", length = 10)
    private String recurrenceId;

    @Column(name = "severity_score", length = 5)
    private String severityScore;

    @Column(name = "color_code", length = 5)
    private String colorCode;

    @Column(name = "corrective_action")
    private String correctiveAction;

    @Column(name = "control_action")
    private String controlAction;

    @Column(name = "comments")
    private String comments;

    @Column(name = "effective", length = 5)
    private String effective;

    @Column(name = "signature", length = 200)
    private String signature;

    @Column(name = "date_completed")
    private Date dateCompleted;

    @Column(name = "nce_category_id")
    private Integer nceCategoryId;

    @Transient
    private String severityId;

    @Column(name = "nce_type_id")
    private Integer nceTypeId;

    @Column(name = "status")
    private String status;

    @Column(name = "discussion_date")
    private String discussionDate;

    @Column(name = "severity", length = 20)
    private String severity;

    @Column(name = "trigger_source_type", length = 50)
    private String triggerSourceType;

    // String, not Integer: QCRuleViolation ids are UUID strings
    @Column(name = "trigger_source_id", length = 36)
    private String triggerSourceId;

    // Default FALSE so manually created NCEs persist false, not null: there is no
    // @DynamicInsert, so an uninitialized Boolean would insert an explicit NULL and
    // override the column default, breaking a future "WHERE NOT auto_generated".
    @Column(name = "auto_generated")
    private Boolean autoGenerated = Boolean.FALSE;

    @Column(name = "westgard_rule", length = 20)
    private String westgardRule;

    @Column(name = "affected_samples_cap_reason", length = 20)
    private String affectedSamplesCapReason;

    @Column(name = "assigned_to")
    private Integer assignedTo;

    // Transient fields - not persisted
    @Transient
    private Date resolutionDate;
    @Transient
    private String resolutionNotes;

    @Override
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Date getReportDate() {
        return reportDate;
    }

    public void setReportDate(Date reportDate) {
        this.reportDate = reportDate;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImmediateAction() {
        return immediateAction;
    }

    public void setImmediateAction(String immediateAction) {
        this.immediateAction = immediateAction;
    }

    public String getNameOfReporter() {
        return nameOfReporter;
    }

    public void setNameOfReporter(String nameOfReporter) {
        this.nameOfReporter = nameOfReporter;
    }

    public String getNceNumber() {
        return nceNumber;
    }

    public void setNceNumber(String nceNumber) {
        this.nceNumber = nceNumber;
    }

    public Date getDateOfEvent() {
        return dateOfEvent;
    }

    public void setDateOfEvent(Date dateOfEvent) {
        this.dateOfEvent = dateOfEvent;
    }

    public String getLabOrderNumber() {
        return labOrderNumber;
    }

    public void setLabOrderNumber(String labOrderNumber) {
        this.labOrderNumber = labOrderNumber;
    }

    public String getPrescriberName() {
        return prescriberName;
    }

    public void setPrescriberName(String prescriberName) {
        this.prescriberName = prescriberName;
    }

    public String getSite() {
        return site;
    }

    public void setSite(String site) {
        this.site = site;
    }

    public Integer getReportingUnitId() {
        return reportingUnitId;
    }

    public void setReportingUnitId(Integer reportingUnitId) {
        this.reportingUnitId = reportingUnitId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getSuspectedCauses() {
        return suspectedCauses;
    }

    public void setSuspectedCauses(String suspectedCauses) {
        this.suspectedCauses = suspectedCauses;
    }

    public String getProposedAction() {
        return proposedAction;
    }

    public void setProposedAction(String proposedAction) {
        this.proposedAction = proposedAction;
    }

    public String getLaboratoryComponent() {
        return laboratoryComponent;
    }

    public void setLaboratoryComponent(String laboratoryComponent) {
        this.laboratoryComponent = laboratoryComponent;
    }

    public String getConsequenceId() {
        return consequenceId;
    }

    public void setConsequenceId(String consequenceId) {
        this.consequenceId = consequenceId;
    }

    public String getRecurrenceId() {
        return recurrenceId;
    }

    public void setRecurrenceId(String recurrenceId) {
        this.recurrenceId = recurrenceId;
    }

    public String getSeverityScore() {
        return severityScore;
    }

    public void setSeverityScore(String severityScore) {
        this.severityScore = severityScore;
    }

    public String getColorCode() {
        return colorCode;
    }

    public void setColorCode(String colorCode) {
        this.colorCode = colorCode;
    }

    public String getCorrectiveAction() {
        return correctiveAction;
    }

    public void setCorrectiveAction(String correctiveAction) {
        this.correctiveAction = correctiveAction;
    }

    public String getControlAction() {
        return controlAction;
    }

    public void setControlAction(String controlAction) {
        this.controlAction = controlAction;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getEffective() {
        return effective;
    }

    public void setEffective(String effective) {
        this.effective = effective;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public Date getDateCompleted() {
        return dateCompleted;
    }

    public void setDateCompleted(Date dateCompleted) {
        this.dateCompleted = dateCompleted;
    }

    public Integer getNceCategoryId() {
        return nceCategoryId;
    }

    public void setNceCategoryId(Integer nceCategoryId) {
        this.nceCategoryId = nceCategoryId;
    }

    public String getSeverityId() {
        return severityId;
    }

    public void setSeverityId(String severityId) {
        this.severityId = severityId;
    }

    public Integer getNceTypeId() {
        return nceTypeId;
    }

    public void setNceTypeId(Integer nceTypeId) {
        this.nceTypeId = nceTypeId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDiscussionDate() {
        return discussionDate;
    }

    public void setDiscussionDate(String discussionDate) {
        this.discussionDate = discussionDate;
    }

    public String getSeverity() {
        return severity;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public String getTriggerSourceType() {
        return triggerSourceType;
    }

    public void setTriggerSourceType(String triggerSourceType) {
        this.triggerSourceType = triggerSourceType;
    }

    public String getTriggerSourceId() {
        return triggerSourceId;
    }

    public void setTriggerSourceId(String triggerSourceId) {
        this.triggerSourceId = triggerSourceId;
    }

    public Boolean getAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(Boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public String getWestgardRule() {
        return westgardRule;
    }

    public void setWestgardRule(String westgardRule) {
        this.westgardRule = westgardRule;
    }

    public String getAffectedSamplesCapReason() {
        return affectedSamplesCapReason;
    }

    public void setAffectedSamplesCapReason(String affectedSamplesCapReason) {
        this.affectedSamplesCapReason = affectedSamplesCapReason;
    }

    public Integer getAssignedTo() {
        return assignedTo;
    }

    public void setAssignedTo(Integer assignedTo) {
        this.assignedTo = assignedTo;
    }

    public Date getResolutionDate() {
        return resolutionDate;
    }

    public void setResolutionDate(Date resolutionDate) {
        this.resolutionDate = resolutionDate;
    }

    public String getResolutionNotes() {
        return resolutionNotes;
    }

    public void setResolutionNotes(String resolutionNotes) {
        this.resolutionNotes = resolutionNotes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        NcEvent ncEvent = (NcEvent) o;
        return Objects.equals(id, ncEvent.id) && Objects.equals(nceNumber, ncEvent.nceNumber);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, nceNumber);
    }
}
