package org.openelisglobal.qaevent.qiconfig.breach;

import java.math.BigDecimal;
import java.sql.Date;
import org.openelisglobal.common.log.LogEvent;
import org.openelisglobal.qaevent.service.NCEventService;
import org.openelisglobal.qaevent.service.NceHistoryService;
import org.openelisglobal.qaevent.service.NceNumberGeneratorService;
import org.openelisglobal.qaevent.valueholder.NcEvent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

@Service
public class QiBreachNceServiceImpl implements QiBreachNceService {

    public static final String TRIGGER_SOURCE_QI_BREACH = "QI_BREACH";

    private static final String NCE_SEVERITY = "CRITICAL";
    private static final String NCE_STATUS = "Pending";
    // Scheduled runs have no logged-in user, so records are attributed to the
    // admin user "1" (same fallback as QcViolationNceServiceImpl) until a
    // dedicated system user exists.
    private static final String SYS_USER_ID = "1";

    @Autowired
    private NCEventService ncEventService;
    @Autowired
    private NceNumberGeneratorService nceNumberGeneratorService;
    @Autowired
    private NceHistoryService nceHistoryService;

    // REQUIRES_NEW so a number collision or failure here is isolated from the
    // evaluator loop and a retry starts clean (mirrors QcViolationNceServiceImpl).
    // The (trigger_source_type, trigger_source_id) unique constraint (migration
    // 051) is the backstop; the pre-check keeps the happy path collision-free.
    @Override
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public NcEvent createBreachNce(String indicatorKey, String periodKey, BigDecimal actualValue,
            BigDecimal actionThreshold, String direction, String unit) {
        String triggerSourceId = indicatorKey + ":" + periodKey;
        NcEvent existing = ncEventService.findByTriggerSource(TRIGGER_SOURCE_QI_BREACH, triggerSourceId);
        if (existing != null) {
            return existing;
        }

        String comparator = "LOWER_BETTER".equals(direction) ? "exceeded" : "fell below";
        String summary = indicatorKey + " " + comparator + " its action threshold in " + periodKey + " (" + actualValue
                + unit + " vs action " + actionThreshold + unit + ")";

        NcEvent nce = new NcEvent();
        nce.setSysUserId(SYS_USER_ID);
        nce.setNceNumber(nceNumberGeneratorService.generateNceNumber());
        nce.setSeverity(NCE_SEVERITY);
        nce.setStatus(NCE_STATUS);
        nce.setAutoGenerated(Boolean.TRUE);
        nce.setTriggerSourceType(TRIGGER_SOURCE_QI_BREACH);
        nce.setTriggerSourceId(triggerSourceId);
        nce.setTitle("QI threshold breach — " + indicatorKey + " (" + periodKey + ")");
        nce.setDescription("Auto-created from QI monitoring. " + summary + ".");
        nce.setImmediateAction("Review the indicator trend and investigate the cause");
        nce.setNameOfReporter("System (QI monitoring)");
        nce.setReportDate(new Date(System.currentTimeMillis()));
        nce.setDateOfEvent(new Date(System.currentTimeMillis()));

        nce = ncEventService.save(nce);

        nceHistoryService.logActivity(nce.getId(), "AUTO_CREATED", "Auto-created from QI threshold breach: " + summary,
                null, null, Integer.valueOf(SYS_USER_ID));

        LogEvent.logInfo(this.getClass().getSimpleName(), "createBreachNce",
                "Created " + nce.getNceNumber() + " for " + triggerSourceId);
        return nce;
    }
}
