update clinlims.test_section set sort_order=10 where name = 'Hematology';
update clinlims.test_section set sort_order=20 where name = 'Biochemistry';
update clinlims.test_section set sort_order=40 where name = 'Cytobacteriologie';
update clinlims.test_section set sort_order=50 where name = 'Bacteria';
update clinlims.test_section set sort_order=60 where name = 'ECBU';
update clinlims.test_section set sort_order=70 where name = 'Parasitology';
update clinlims.test_section set sort_order=80 where name = 'Immunology';
update clinlims.test_section set sort_order=90 where name = 'Mycobacteriology';
update clinlims.test_section set sort_order=100 where name = 'Endocrinologie';
update clinlims.test_section set sort_order=110 where name = 'Liquides biologique';
update clinlims.test_section set sort_order=120 where name = 'Serologie';
update clinlims.test_section set sort_order=130 where name = 'VCT';
