UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Compte des Globules Blancs(Sang)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Compte des Globules Rouges(Sang)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Hemoglobine(Sang)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Hematocrite(Sang)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'VGM(Sang)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'TCMH(Sang)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'CCMH(Sang)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Plaquettes(Sang)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Neutrophiles(Sang)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Lymphocytes(Sang)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Mixtes(Sang)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Monocytes(Sang)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Eosinophiles(Sang)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Basophiles(Sang)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Vitesse de Sedimentation(Sang)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Temps de Coagulation en tube(Sang)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Temps de Coagulation(Sang)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Temps de saignement(Sang)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Taux reticulocytes - Auto(Sang)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Taux reticulocytes - Manual(Sang)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Temps de cephaline Activé(TCA)(Plasma)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Temps de Prothrombine(Plasma)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'INR(Plasma)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Facteur VIII(Plasma)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Facteur IX(Plasma)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Heparinemie(Plasma)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Anti-Thrombine III (Dosage)(Plasma)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Anti-Thrombine III (Activite)(Plasma)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = $$Azote de l'Uree(Serum)$$);
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Uree(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'creatinine(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Glycemie(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Glycemie(LCR/CSF)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Proteines(LCR/CSF)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Chlore(LCR/CSF)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'glycemie(Plasma)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Albumine(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'α1 globuline(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'α2 globuline(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'β globuline(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'ϒ globuline(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Phosphatase Acide(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Chlorures(Plasma hepariné)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Chlorures(Urines/24 heures)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'CPK(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Amylase(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Lipase(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Chlorures(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Sodium(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Potassium(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Bicarbonates(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Calcium(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'magnésium(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'phosphore(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Lithium(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Fer Serique(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Bilirubine totale(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Bilirubine directe(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Bilirubine indirecte(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'SGOT/ AST(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'SGPT/ ALT(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Phosphatase Alcaline(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Cholesterol Total(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Triglyceride(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Lipide(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'HDL(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'LDL(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'VLDL(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'MBG(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Hémoglobine glycolisee(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'LDH(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Triponine I(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Ph(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'PaCO2(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'HCO3(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'O2 Saturation(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'PaO2(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'BE(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Glycémie(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Glycemie Provoquee Fasting(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Glycémie provoquée 1/2 hre(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Glycémie provoquée 1hre(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Glycémie provoquée 2hres(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Glycémie provoquée 3hres(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Glycémie provoquée 4hres(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Glycémie provoquée(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Glycemie Postprandiale(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Azote Urée(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Urée (calculée)(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Créatinine(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'SGPT (ALT)(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'SGOT (AST)(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Cholestérol total(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'HDL-cholestérol(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'LDL-cholesterol (calculée)(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'la porphyrineVLDL – cholesterol (calculée)(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Triglycéride(Serum)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'Acide urique(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Chlorure(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Calcium (Ca++)(Serum)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Protéines totales(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Creatinine(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Creatinine(Sang)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Creatinine(Plasma)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'SGPT/ALT(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'SGPT/ALT(Sang)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'SGPT/ALT(Plasma)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'SGOT/AST(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'SGOT/AST(Sang)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'SGOT/AST(Plasma)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'CRP Quantitatif(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'CRP Quantitatif(plasma)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'C3 du Complement(Sang)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'C4 du complement(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'C3 du Complement(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'C4 du complement(Sang)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Facteur Rhumatoide(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'pH(Liquide Spermatique)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Fructose(Liquide Spermatique)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Volume(Liquide Spermatique)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Compte de spermes(Liquide Spermatique)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Formes normales(Liquide Spermatique)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Motilite STAT(Liquide Spermatique)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Motilite 1 heure(Liquide Spermatique)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'Motilite 3 heures(Liquide Spermatique)');
UPDATE clinlims.test_result SET significant_digits = 3 WHERE test_id=(select id from clinlims.test where description = 'Densite(Urines)');
UPDATE clinlims.test_result SET significant_digits = 1 WHERE test_id=(select id from clinlims.test where description = 'pH(Urines)');
UPDATE clinlims.test_result SET significant_digits = 0 WHERE test_id=(select id from clinlims.test where description = 'CD4 Compte Absolu(Sang)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'CD4 Compte en %(Sang)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'PPD Quantitatif(In VIvo)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Prolactine(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'FSH(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'FSH(Plasma hepariné)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'LH(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'LH(Plasma hepariné)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Oestrogene(Urines/24 heures)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'Progesterone(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'T3(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'B-HCG(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'T4(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'TSH(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'TOXOPLASMOSE GONDII IgG Ac(Serum)');
UPDATE clinlims.test_result SET significant_digits = 2 WHERE test_id=(select id from clinlims.test where description = 'TOXOPLASMOSE GONDII Ig M Ac(Serum)');
